### ISSUE TITLE
Let's talk Lava Web Spider miniboss

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#166]
Another one of those. Basically a place to pen down ideas we get.

200 health, like all minibosses.

Note: This mob should not be affected by Bane of Arthropods. He is arthropomorph, but only consists of magma and volcanic rock bits.

Both Magma Crawlers/Blasters and the boss himself do not get slowed down by the Magma Webs, but they will get slowed down by regular webs.

ATTACKS:

- Bite. Basic melee attack, does 6 damage. Nothing special. MELEE.
- Summon. He spawns 1-3 Magma Blasters and 2-6 Magma Crawlers. It has a cooldown of 30 seconds. NO CLASS.
- Eruption. He jumps up into the air, and when he lands, in various spots, upwards lava thingy-block-like-things will spawn, which will explode when they land and leave a little bit of flowing lava there (which decays, so the battlefield won't get too messy). 15 seconds cooldown. AOE.
- Rock Missile. He shoots a piece of Volcanic Rock at you. This does 4 damage, and it pierces armour. It also severely damage the durability of your armour. 15 seconds cooldown. RANGED.
- Web Spinning. It wraps you in two Magma Webs (one for your legs and one for your upper body), which set you on fire. Upon destroying it, it spawns a lava source block. MELEE.

POSSIBILITIES:

- Flame Ring. He spawns a ring of flame particles around him, which knocks people back and sets them on fire.

ANOTHER NOTE:

He can destroy blocks, all except for Volcanic Rock, Obsidian, Bedrock, and basically all other unbreakable blocks. He only does that when he needs to get to his enemy if he is blocked by blocks. All blocks just break (and drop nothing, they are incinerated), but if the block is materialStone or whatever, it will spawns a lava source block.

It lives in the Volcano dungeon we're going to add to the Volcanic Desert.

MAGMA CRAWLER:

- HP: 10.
- Attack: Does 2 damage, sets you on fire. He can also spray fire onto you, which also sets you on fire and hurts you for 1 HP per second.
- Drops: We'll see, such a small mob doesn't really need a drop I think.

These are meant to die easily.

MAGMA BLASTER:

- HP: 20.
- Attack: Does 4 damage, causes a tiny explosion. He can also shoot a ghastly fireball.
- Drops: 0-2 Fire Charges.

All the mobs named above are resistant to fire- and explosive damage.

**Comment by vadis365** [comment]
Nah
