### ISSUE TITLE
Erebus Cooking  - Let's do it right this time.

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#167]
COOKING APPLIANCES

We should start with getting the different things ready to actually prepare the food.

- Stove
You can place up to 4 food items on top of it (in-world), on the 4 8x8 ''quarters'' on the top of it, and it will cook them (which will be fancy, will be explained once we get to it).

You can open up the front side of the block and stuff in fuel, then light it with Flint&Steel or other fire creation methods. Fuel will burn 4x longer.

- Kitchen Counter
You put together your food (not your smoothies) here. It opens a little GUI with room for food and modifiers, it will actually be pretty easy.

- Mortar and Pestle
Used to grind various leaves into dusts, currently only Firebloom and Weeping Blue Petals though. A simple right-click with the thing you want to grind works fine.

- Mixer
Input a bucket of Milk, Honey, Beetle Juice or Anti-Venom (it stores 1000 mB, but you NEED to use a bucket just to keep it simple), and add up to 3 fruit ingredients. Then, you can add up to 3 modifiers as well. You then mix it by right-clicking the Mixer with a Spoon. You can then right-click it with a Bottle to get a Fruit Smoothie with the traits you made. This only drains 250 mB.

Shift-right-click it with an empty hand to remove the last modifer/fruit ingredient you added. 

The rendering for a ''finished smoothy'' will be funky (texture-wise), I'll explain it once we get to that.

MAKING FOOD

- Ingredients

You've got two types of ingredients: Main Dish and Tastemakers. The former decides the base hunger and saturation value, the latter adds effects to it. When making your food, the ''base dish'' NEEDS 1/2/3 ingredients (as specified below), but modifiers are optional, and you can add UP TO 3, but ofcourse a minimum of 0.

MAIN DISH:

- Vanilla meat (Steak, Chicken, Pork, including cooked)(1 per dish).
- Vanilla vegatables (Potato, Cooked Potato, Carrot)(2 per dish).
- Erebus meat (Titan Chop, Tarantula Paw, Cricket Leg, including cooked)(1 per dish).
- Erebus vegatables (Bamboo Shoot, Turnips)(2 per dish).
- Erebus Beetle Larvae (up to 3 per dish, Raw gives Nausea II for 5 seconds, which stacks).
- Fruit cannot be used (aka Middle Fruit, Apple and Melon Slice) for regular food.

Vegatables need a Bowl to be put in, and cannot be combined with meat substances (since those only allow 1 per dish, excluding Beetle Larvae which they can't be mixed with either).

You may also choose to put these ingredients on Bread, which creates a Sandwich. A Sandwich gives more saturation and food.

TASTEMAKERS (up to 3 per dish):

- Honey, adds a Regen II for 5 seconds (duration stacks).
- Camouflage Powder, gives Invisibility for 15 seconds (duration stacks).
- Moss Ball, nullifies any potion effects you might get from the dish (adding more than 1 has no use).
- Middle Fruit Seeds, adds a 1.1x multiplier to the saturation (multiplier stacks).*
- Ground Weeping Blue puts you out when you are on fire, but gives you Slowness II for 10 seconds.
- Ground Firebloom sets you on fire for 10 seconds, but gives you Strength I for 30 seconds.
- Repellent gives you Nausea II for 30 seconds, but keeps arthropod mobs away from you.
- Nettle Flowers adds a 1.5x multiplier for any potion effect you can get from the dish, and it stacks.**
- Gold Nugget gives Absorption for 15 seconds, each Gold Nugget adds 1 heart.
- More to be added once we get some more inspiration. 

* 1.1^2 = 1.21 and 1.1^3 = 1.331 for the multiplier.
* 1.5^2 = 2.25, adding 3 (1.5^3 = 3.375) is only useful when you have a MAIN DISH that already gives you a potion effect, like the Golden Apple or Titan Chops.

SPECIAL COMBOS

- Ground Weeping Blue + Ground Firebloom nullifies the Strength and the Slowness II, and gives you a Speed II boost for 20 seconds.
- Gold Nugget + Honey adds a 1.5x multiplier to the Honey's duration (2 Golden Nuggets + 1 Honey = 2.25 x 5 = 11.25 seconds of Regen, 1 Golden Nugget + 2 Honey = 15 seconds of Regen). Ofcourse, this does not negate the Absorption effect.
- More coming once I get some more inspiration.

FRUIT SMOOTHIE:

Combining Honey, Milk, Beetlejuice or Anti-venom with fruit (Apple, Melon Slice, Middle Fruit) gives you a pretty filling thingy. Some stats:
- Up to 3 fruits can be combined.
- The fruits add onto the total saturation and food value of the total smoothie, but you need to apply a formula specified down below to calculate the sat/food value of the smoothie itself.
- One (bam)bucket of the liquid yields 4 fruit smoothies.
- Honey has a Regen II effect for 10 seconds per smoothie, Milk heals all potion effects (but does not negate the ones you might get from the modifiers), Beetle Juice is like milk but also removes the Bot Fly Larvae, and Anti-venom does its regular job as well.
- Same modifiers apply, but with different numbers (going to specify it in a comment), except for Honey, which can't be added in when Honey is your base fluid.
- Modifiers, yet again, are not mandatory. You can add 0-3 of them.
- The smoothie basically follows a formula to calculate how much it feeds/saturates like this:

((A + B + C)/4), where A B C are the saturation/hunger value of the 3 different ingredients, and since you can get 4 smoothies out of 1 mix, you then divide it by 4 to keep it good.

MOD COMPATIBILITY AND API THINGS:

API-wise, modders should be able to add modifiers of their own and specify its effects. Dunno how you're going to do that, but it should just pretty much be very easy to add new modifiers and foods.

As always, just keep it a fluid, or adaptable, system. As little hardcoding as humanly possible. Just... I have no idea, but people should just be able to have a swell time.

**Comment by vadis365** [comment]
Never going to happen. Closing although I like the idea
