### ISSUE TITLE
Modular Umberfurnace multiblock concept - Needs feedback

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#172]
A concept I've been working on, which allows you to craft a 3x3x3 multiblock out of various parts, depending on your resources and taste. Following parts are planned:

- Umberfurnace Core - Base thing to make your machine function, place to access its GUI.
- Umberfurnace Item Port - Allows you to insert and extract items. 
- Umberfurnace Magma Port - Allows you to insert and extract lava.
- Umberfurnace Tank - Allows you to store lava. Lava speeds up progress.
- Umberfurnace RF Coil - This gives you the ability to smelt using RF. This disables the solid fuel slot.
- Umberfurnace Redcontrol - Allows you to turn your furnace on and off.
- Umberfurnace Slot - Adds another slot to the GUI for all of your cooking needs.

FURNACE BEHAVIOUR:

The furnace has to be constructed out of 26 blocks (the centre needs to be left clear), in a basic 3x3x3 shape. You can use Umberstone, Umbricks, Smooth Umbertile and Smooth Umbertiles to construct your furnace, and basically fill in all the blank spots.

MODULES:
The core is required to ''form'' the multiblock. You right-click it to access the GUI. The furnace starts with 3 slots, and as such fuel is consumed 3x faster than normal. Also, there will be a 16-buckets worth lava tank already.
- The Tank makes the items smelt faster, similar to small Umberfurnace behaviour: the more Lava present, the more heat there is, thus the faster it smelts. 
- The RF Coil acceps RF to heat up your furnace, but disables the solid fuel slot. Lava will also make this more efficient, since faster burning = less RF per smelt (since it uses RF/t, right?).
- The Item Port has 3 modes: Input, Fuel and Output. Input accepts items and spreads them evenly over the available slots (if possible), output pulls out items from the finished result slot, and fuel inserts solid fuel into the fuel slot. The ''fuel'' mode is disabled when an RF Coil is detected. There is also the base block, which is the one you'll have in your inventory, but upon placing it into your world it turns into a port in Input mode.
You can ofcourse use multiple sides to insert or extract items, but you'll need a different one for each.
- The Magma Port accepts lava, easy. 
- The Tank stores another 16 buckets of lava (meaning you can get even more lava, thus more speed!).
- The Slot adds another slot for your smelting needs, really.
- The Redcontrol module gives you the ability to turn off your furnace if you don't want it to run.

FUEL CONSUMING:

Any solid fuel lasts for a certain amount of ticks. The amount of ticks it lasts is converted into ''Solid Fuel'' (a liquid in the internal tank for it... don't question it :3). Each active slot (with an item that is being smelted) consumes 1 mB per tick. That's it, really. Simple enough.

**Comment by kutschkem** [comment]
So, basically very similar to ModularSystems? https://github.com/TeamCoS/Modular-Systems
Instead of doing it yourself, maybe just add default configuration for modular systems?

**Comment by ganymedes01** [comment]
Pretty much, that's why nobody has done it yet =P

**Comment by vadis365** [comment]
Closing due to reasons stated above :P
