### ISSUE TITLE
Silo Access block

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#190]
This is used to help automate the Silo. It must be placed on top of the middle silo block and will replace the roof.

Functionality:
It acts as a basic inventory for vanilla and other mod purposes (they can interact with it like they would with a chest, interacting with the inventory of the multiblock). You can input with hoppers, pipes, etc. It will also allow pipes and other forms of item transportation to extract from it like those would with any normal inventory.

Recipe:

V H V
H P H
V H V

V = Varnished Planks
H = Hopper
P = Piston

All the resources you should need are on the Dropbox in a folder named ''Silo Access''. I also added textures that should be applied in a similar manner to how the Composter and Bamboo textures are applied, but it's up to you which you decide to use.

Hopefully this can be done!

**Comment by vadis365** [comment]
Closing this as it will probably never be done - the silo works with BC pipes and TE itemducts at the moment anyway.
