### ISSUE TITLE
Bamboo Shoot Problems

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#238]
Bamboo shoots DO NOT WORK WELL!
Had several reports of this from people, honestly, they just don't seem to grow (or bonemeal).
Not my fault, f*#k it, I'm going to nerf them - sorry Dan...

**Comment by Zsashas** [comment]
I don't understand the problems everyone has been having growing Bamboo, honestly. On a Modsauce II server, I have several Bamboo Shoots planted near my house in random places, and they all grow fine. I need Bamboo infrequently enough for it to grow decently. It just takes slightly longer than Sugarcane, is all. I also found an overworld island with Bamboo growing on it, and this time I was smart enough to leave the bottom blocks so I never have to worry about it ever again.

**Comment by vadis365** [comment]
closing for now due to mixed reports, works for some and not for others.

**Comment by purpleposeidon** [comment]
I planted some shoots & left them alone, and eventually learned that they do actually grow, but more akin to sugarcane than trees, which is what I had been expecting. Maybe they shouldn't accept bonemeal.

**Comment by Zsashas** [comment]
Using the latest Erebus version, Bamboo no longer grows for me. I have no idea how I made it work the first time, but it has been several RL days now.
