### ISSUE TITLE
Improve woods localization

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/TheErebus#245]
It's a bad thing using one "wood type"(I mean Baobab, Eucalyptus and etc) line for "Wood", "Planks", "Stairs", "Leaves" and etc. Because it's making localization on other languages painful. It's should be replaced with "wood type" for "Wood", different "wood type" for "Planks" and etc. Like here for example: https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/resources/assets/biomesoplenty/lang/en_US.lang#L198

**Comment by Adaptivity** [comment]
Also, Umberstone Slabs should have some strings like "Stairs" or "Walls" have: https://github.com/ganymedes01/TheErebus/blob/master/src/main/resources/assets/erebus/lang/en_US.lang#L68
@ganymedes01 @vadis365 any news about it?

**Comment by ganymedes01** [comment]
The wood translations can be tweaked. I'll look into it.

Not quite sure what you mean on the second comment?

**Comment by Adaptivity** [comment]
Basically, Slabs from Umberstone localized like Slab + these names(https://github.com/ganymedes01/TheErebus/blob/master/src/main/resources/assets/erebus/lang/en_US.lang#L130). But they should have unique names(strings) like "Umberstone Stairs" or "Umberstone Walls".

**Comment by Adaptivity** [comment]
just an FYI, Russian translation is finished. Just waiting on this issue.

**Comment by ganymedes01** [comment]
Still not sure what you want, sorry XD
Submit a PR changing the english lang file to what you'd prefer it to be, and then I'll change the code so the matches it :3

**Comment by vadis365** [comment]
Please don't mess with the English lang file until after the weekend - I am hoping to release an update on Sunday :)

**Comment by Adaptivity** [comment]
An example what I mean -> http://pastebin.com/47KFLPW7 It should be done for everything which uses %s tags. (i.e  Wood, Planks, Stairs, Leaves, Sapling, Slab, Flower, Flower Stigma, Petal, Flower Bulb) You can leave en_US.lang as is but add something like "custom names" for names I provided above. So, by default if .lang file contains only "tile.erebus.log.name", it uses this name but if there are present names like I provided in pastebin link, it skips "tile.erebus.log.name" and uses these names from pastebin.

**Comment by ganymedes01** [comment]
Now that the pre-release is out, I'll work on this later in the week :3

**Comment by vadis365** [comment]
Go for it mate.
Going back to TT's this week - neglected it for too long.

**Comment by vadis365** [comment]
@ganymedes01 
I guess I cant fault you... you didn't actually say which week ;)

**Comment by vadis365** [comment]
:P

**Comment by Adaptivity** [comment]
still... not yet ready... :D
