### ISSUE TITLE
New Crop - Cabbages

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#246]
How about a new crop?
Swamp plants are useless what about making them like grass but they drop cabbage seeds randomly?
They could be grown and cabbages, turnips, overworld potatoes and carrots *and mushrooms * with titan chops/beef could be grafted in to a hearty stew or eaten on their own. Instead of a burp after eating you would make a fart noise :P
With this also comes a use for the butterfly mob.
Butterflies, when flying over a cabbage plant could descend and lay an egg.
This egg could hatch in to a caterpillar. Caterpillars could be like beetle lava (low level griefing) they would eat say up to 8 cabbages and turn in to a butterfly.
Could be fun.

**Comment by vadis365** [comment]
Done.

**Comment by ganymedes01** [comment]
damn British folk steal our jobs
