### ISSUE TITLE
Game Crash in Erebus biome ID cannot be higher than 127

### ISSUE THREAD

**Issue by Bogdan-G** [ganymedes01/TheErebus#247]
Hello, run Erebus 0.2pre12 & GC build 250 and custom config:
biomes {
    I:"Elysian Fields"=122
    I:"Fields - Forest"=123
    I:"Fungal Forest"=124
    I:"Submerged Swamp"=218
    I:"Subterranean Savannah"=125
    I:"Ulterior Outback"=126
    I:"Underground Jungle"=121
    I:"Volcanic Desert"=127
}
New biome "Submerged Swamp" and new custom ID.
Game crash in Initialized:
http://pastebin.com/hg6pCArn

Error code in Erebus?

**Comment by ganymedes01** [comment]
"Erebus biome IDs cannot be higher than 127!"

That means erebus biomes cannot be bigger than 127. Use smaller numbers.

**Comment by Bogdan-G** [comment]
But Biomes O' Plenty, Thaumcraft 4, ExtraBiomesXL, ReikaMods, Rediscovered, Buildcraft can using 127+ biomeID, why?
