### ISSUE TITLE
Add capstones for dungeon pyramid

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#255]
As part of the dungeon progression system these blocks will be required.
The capstones should be unbreakable.
The way to enter the pyramid in the maze dungeon will be by placing 4 items (the new idols found in each corner of the maze in petrified chests) on to the capstones. This will 'unlock' the entrance and remove the capstones so you can get in to the boss dungeon. I guess the capstones should be half blocks or some sutch. Upon placing all 4 idols the capstones should have some sort of animation or particles or some shit. The capstones would be a small multiblock structure.
Maybe render the idol item on to the top of the blocks, or have the texture change, to show they have been placed. IDK if you want to do this or not? If not I can.

**Comment by ganymedes01** [comment]
Have you added the idols yet?

**Comment by vadis365** [comment]
Yes. the idols are just items - I made them their own class rather than just adding them to the materials list - just in case they was a specific thing they had to do - without making it a pain to edit the materials.
All 4 items are added and have their own enum for meta.

**Comment by ganymedes01** [comment]
I'll make it so the capstones are unbreakable but once there's an idol on them they can be mined with a pickaxe.
Once you have a multiblock structure in mind I can make it fancier (like make them disappear with some crazy laser show or something)

**Comment by vadis365** [comment]
Awesome - I am working on the mobs that drop the idols atm.
Once I am happy with them - I'll start on the pyramid and the capstone laser show can commence...
