### ISSUE TITLE
Need a new Boss Drop Idea

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#263]
The dungeon is pretty much done. :P
The Mini bosses, new mobs, spawners, dungeon mechanics world gen and Main boss fight are done.
Loot chest contents need updating to reflect the newer mod content - I have asked for ideas on the MC forums to get people involved. At the same time #262 should be addressed.

We just need something epic as a prize for beating the dungeon boss.
Atm it drops the crystal thing so the wand of animation is craftable again (stupid to remove that feature imho) and an egg like the tarantula (to be used for a later thing).
Ideas please. If no-one comes up with anything I will just make a new O.P. sword as the prize.
I have done 99% of this thing already....could do with some fresh input.

**Comment by ganymedes01** [comment]
Hammer sounds good.
One thing that I think would go well is some sort of trophy. Sort of like how Twilight Forest does it. Just a pointless token that doesn't do anything, but that you can exhibit in your house :3

**Comment by vadis365** [comment]
Started hammer - feel free to finish it off if you can be arsed - I need zzzzzzzzzzzz

**Comment by vadis365** [comment]
Done - nearly ready for release - just need play testers and some code cleaning
