### ISSUE TITLE
Replacing Temple Brick with Gneiss Bricks

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#266]
Can we use the GneissDungeonBricks for the dungeon instead of the Temple Brick ones? Also, tell me which textures for the dungeon are based on the Temple Brick one so I can change them accordingly if this goes through.

No milestone since I'm utterly lost.

**Comment by vadis365** [comment]
Nope - that will break a shit-ton of my last months work.
Closing as we  resolved this.. ;P
