### ISSUE TITLE
Make all the Gneiss dungeon blocks harder to destroy.

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#267]
I destroyed one by accident while trying to destroy a spawner. That's a bit annoying and it also kinda closes off part of the dungeon (had no blocks on me). But yeah, please :D.

**Comment by vadis365** [comment]
Okee-dokee - I'll do that.
Also had a request to make them TNT proof - which also is a good idea.
It will stop people just blasting their way through....

**Comment by vadis365** [comment]
Done.
