### ISSUE TITLE
Let's nerf the crap out of locusts [GAMEPLAY UPDATE]

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#270]
Locusts. They drop an item needed to make something super awesome, but they are really strong. Being in certain biomes for 5+ minutes results in you getting bent over and raped by a whole horde of them.

How can we get rid of this? Here's my idea:
- Grasshoppers DON'T breed themselves. 
- You can breed them using x item (something plant matter).
- Their babies and generations onward do infact breed.

This means you can make a farm and aren't forced to get raped. The Erebus should be difficult, but this mechanic is just kinda broken early on. Hopefully you can agree with this (grasshopper breeding isn't removed, just gated).

**Comment by vadis365** [comment]
I don't like the idea of farming grasshoppers - but I could nerf the conditions for their breeding.
I could make it so if there is a locust within say 16 blocks then grasshoppers stop turning in to locusts.
