### ISSUE TITLE
bug with grave

### ISSUE THREAD

**Issue by XBlackLeopardX** [ganymedes01/TheErebus#273]
I've noticed that the grave (pile of bones) does not save tinkers' construct tools in the inventory and are lost when you die as for how often it happens it happens all the time and i am using the newest version of all mods and forge

**Comment by vadis365** [comment]
This is now fixed it was overwriting 4 inventory items with the armour - whoops.
I would suggest disabling the block 'o bones in the config until the next release.
Sorry about that.
