### ISSUE TITLE
Aesthetic tweaks to the Water Strider mob

### ISSUE THREAD

**Issue by PCAwesomeness** [ganymedes01/TheErebus#275]
TBH, the Water Strider seems good, but it could use some more work. Here's what I'd like to see (done exactly in that order)...

1: Different posture (it should be standing on blocks or the surface of water)
2: Animated legs 
3: When it dies, it should make that same squishing noise as all the other insects

I hope this could get added!

**Comment by vadis365** [comment]
There is no such mob. It is called the pond skater ;P

1. Posture is fine and correct for what it is.
2. Sure - this was overlooked but, I'll make them move a bit.
3. Whoops, probably forgot to do that  (had to rush that mob a bit).

Cheers,
Me.

**Comment by PCAwesomeness** [comment]
I like to call it the water strider, since it is in one of my books.

1: OK...
2: Thank you!
3: Thank you!
