### ISSUE TITLE
Big Bamboo Crate breaks badly

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#278]
(I didn't even know that was a thing!)

**Comment by ganymedes01** [comment]
wut? badly how? XD

**Comment by vadis365** [comment]
???

**Comment by purpleposeidon** [comment]
Like so: http://i.imgur.com/Q9WZ07E.png

**Comment by blarging2000s** [comment]
When the "main crate" is broken it doesn't update the other's models so they become invisable.
When any of the others are broken the rest aren't updated causing what looks like phantom blocks but are air blocks with the "main crate's" model sticking into it.

**Comment by vadis365** [comment]
Yeah this is a real issue. It never used to do this, so something must have changed a while back. It may be as simple as marking the block for an update and re-rendering it.
