### ISSUE TITLE
Items debatable for removal

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#282]
Here a list of items we could remove.

- Caveman Club.
                    Reason: it doesn't add anything special, it's just a fancy sword.

- All animation stuff.
                   Reason: Nobody is working on it anyway, better get rid of it.
                   We need to keep the code for it in a different place though, it needs to be saved for later.

- Block Extractor.
                   Reason: no cohesivity, seems out of place.

- Fiddlehead, Fern, Bullrush, Desert Shrub, Droughted Shrub, Weeping Blue Bell, Swamp Weed thing
                   Reason: entirely redundant, don't add enough gameplay.

- Horn of the Swarm.
                  Reason: doesn't really add much.

- Lifeblood
                  Reason: 0 use, dunno?

**Comment by vadis365** [comment]
Club - I agree
Animation stuff - yup
Block extractor - yup redundant now ore gen is different
Horn of the swarm - yeah - pretty poo - maybe recode it to make bees instead?
Plants should stay - they add atmosphere and lots of them are now used in recipes for the smoothies.
Life Blood is a drop that could be removed as it is from Leeches and Blood Snails (which are planned for removal) - but maybe given to the mosquitos instead ;)

**Comment by Dylan4ever** [comment]
The plants I listed above are the ones I feel at the least atmosphere and could be quite easily removed.

However, let's say the Fern, Fiddlehead, Droughted Shrub and the Swamp Weed thing then.

I like the bullrush, but what is it used for?

**Comment by Dylan4ever** [comment]
Actually, the Fern and Fiddlehead can be kept. They are basically fancy tall grass, I don't mind them much (and they do have a use, they drop seeds right?).

**Comment by vadis365** [comment]
Bullrush lets you make paper and also the rather fun - rolled up newspaper

**Comment by Dylan4ever** [comment]
It does? It never dropped shit for me.
