### ISSUE TITLE
Water Striders behaviour

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#285]
So, let's see:
- I don't know how falling into water works right now, but it seems like you just randomly land on a water block at a random depth.
So, let's make it so that: when falling, the effect of the boots is deactivated. I hope there is some whileFalling hook or something.
- When you push shift, the effect should be deactivated.
- You can ascend twice as fast in water while wearing these.

Do these sound like good ideas?

**Comment by vadis365** [comment]
Closing because it has been open for ages and not done. Will re-open one day, I guess :P
