### ISSUE TITLE
Coherent armour system: upgrade slots for the exo-armour. Basic mechanics.

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#286]
Basics:
- Shift-right-clicking while holding a piece of exo-armour will open an inventory. These have a varying amount of slots depending on the piece.
Helmet: 2
Chestplate: 3
Leggings: 2
Boots: 1

You can only input valid upgrade items (we will specify which items work as upgrades by giving them some flavour text, like 

''Water repellent 
Exo-upgrade: Water Striding.'')

I will prepare a GUI for these.

- When the durability of a piece of armour runs out, all items inside will drop in front of you (boots with elastic fibre break. The elastic fibre is dropped in front of you. That stuff).

**Comment by vadis365** [comment]
Closed due to it's not happening yet.
