### ISSUE TITLE
Gliding behaviour change

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#288]
Instead of a keybind, let's make it so that you will always glide, but pressing shift will negate the gliding effect (disable it until you stop pressing shift).

So.
- Remove the keybinding for the gliding.
- Alter gliding behaviour so that it always makes you glide unless you press shift.
- Basically make shift disable the gliding ability and such.

Less keybindings = better :3.

**Comment by vadis365** [comment]
Seems pointless and tbh annoying.
I would rather keep it as it is - rather than having to sneak all the time whilst wearing armour.
I think this will break the items usefulness and also it will affect the powered one.

**Comment by vadis365** [comment]
Less keybindings = better :3. - maybe
but making someone hold down shift constantly is just plain stupid.

**Comment by Dylan4ever** [comment]
We could also make the player glide while shifting or something... I dunno, looking at it now, it doesn't sound too great.

I do think having lots of keybinds is annoying though (meh i can change them to my liking anyway)... but yeah, you are right. Gonna close this. I'm a dummy :3.
