### ISSUE TITLE
Stew pot recipe conflicts with Growthcraft

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#291]

**Comment by vadis365** [comment]
Which part of it is causing the conflict?
I'm sorry I don't have growthcraft installed atm.
is it the cauldron thing?

**Comment by purpleposeidon** [comment]
Yes.

**Comment by vadis365** [comment]
ummm.... I don't know the growthcraft recipes - is it cauldron -> stewpot?

if so I can change it easily by adding a random Erebus item to the recipe ;)

**Comment by ganymedes01** [comment]
I'll make it cauldron + stick.
Every stewpot needs a mixing spoon :3
