### ISSUE TITLE
Buff titan stew

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#292]
Titan stew looks so delicious! Omnomnomnom! But even though it fills up your entire hungerbar, it doesn't seem worthwhile to carry around since it doesn't stack, and it requires the pot, and it has to be cooked. Eating it at home before leaving hardly seems worthwhile either, since really you could just eat more steak. How about 6 minutes of saturation? 1 minute's too short, and 10 minutes is probably too long.

The two-steak recipe variant seems kind of cheap to me tho; it should probably give a weaker effect?

**Comment by vadis365** [comment]
Good Ideas - I'll see about tweaking it for the next release :)
