### ISSUE TITLE
More rotten stumps and fallen logs in the mushroom biome

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#294]
I'd like there to be more, to make the fungal forest feel more like a rotten forest.

I'd also like there to be some much bigger rotten stumps that are still hollow but twice or thrice as high, maybe with some bare branches too.

**Comment by vadis365** [comment]
Meh. It's fine atm.
We do need some more mobs for this biome though.
Closing because I'm in the mood to close things today. :)
