### ISSUE TITLE
Antlion dungeon minor changes

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#296]
- The mob spawners should be Scorpion and Antlion spawners (remove the magma crawlers). These should not be in the ceiling, but in corners. 
- No lava would be better (also, make the wall blocks just incredibly hard to break like the wasp dungeon walls, with no tool actually offering a speed boost, so static mining speed).
- Move the structure to spawn in the Ulterior Outback.

The Volcanic Desert doesn't seem like the right place.

**Comment by vadis365** [comment]
Don't agree with any of this...
The Antlion is a volcanic desert mob only.
Gneiss makes lava.
Took me ages to code and a 'little tweak' it isn't - it would involve a major re-write of the whole dungeon which tbh I am against because it took me a month solid coding to make it.

**Comment by Dylan4ever** [comment]
I feel like the antlion dungeon would work better in the outback, since the desert is lots of lava spam that could easily ruin such a magnificent structure. 

I actually feel like the antlion should spawn in the outback too, but that's meh.

Suggested the wall blocks to simply become really hard to break (so people can still move through if they want, but are heavily discouraged), since I don't really like the lava mechanic. However, it works, so there's no rush to change it.

Didn't know it'd be so much work, sorry for lacking coding knowledge.
