### ISSUE TITLE
Remove fire ants (all types), move Magma Crawlers to spawn naturally in the volcanic desert

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#297]
Basically that. Fire ants are just another type of ants, and since I had plans for the volcano dungeon to have magma crawlers, i feel like this would be cooler. 

Hopefully you agree.

**Comment by vadis365** [comment]
Nope.
This ruins a lot of hard work of which I will not spend the time re-coding it.
There is no Volcano dungeon so it is pointless breaking the game for people as I probably won't code it and no-one else wants to either.

**Comment by Dylan4ever** [comment]
Alrighty, we will see how it works out in the future then. I understand your view.
