### ISSUE TITLE
The antlion dungeon generates strangely

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#301]
![2015-05-12_18 31 23](https://cloud.githubusercontent.com/assets/5971389/7592716/3066ec36-f8d5-11e4-8207-11292c23056c.png)

First one I found in-game... And it looks like this. This totally doesn't do the thing justice. How does it check if there's space to generate (does it even)?

**Comment by vadis365** [comment]
Find a Worldgen coder then. I do mobs.

**Comment by Dylan4ever** [comment]
Understood. Just pointing it out, shouldn't've assigned you. Sorry.
