### ISSUE TITLE
Recipe request:

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#306]
In the Offering Altar, make Jade work (in place of Emeralds) too. So you have 2 recipes for it: obsidian, diamond, emerald and obsidian, diamond, jade.

Reason? I got stuck in the Erebus. Forgot my Staff of Gaea and I can't cheat one in, but I don't think there are any Emeralds in the Erebus (or they are at least so hella rare that it's nigh impossible to find them).

Thanks in advance, I wanna go home :{.

**Comment by vadis365** [comment]
Emeralds are very common in the Erebus - look harder!

**Comment by Dylan4ever** [comment]
Found some at long last, too bad I died like 3 times already before that (thus returning to the overworld), so it was of no use.
