### ISSUE TITLE
Reduce Wasp and Zombie Ant attack range

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#308]
Tried fighting a zombie ant... He hit me before I could hit him. T'was crazy, had to run like a bitch.

And wasps are just way too strong with their current attack range.

**Comment by vadis365** [comment]
That is changed already - you wimp!

**Comment by Dylan4ever** [comment]
I'm using the most recently released version and especially the Zombie Ant is still ridiculous. Am I not seeing something (I don't consider it unlikely)?
