### ISSUE TITLE
Config option to turn off Swamp Vents

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#310]
They lag me out so damn much, even with particles on minimal.

However, I still like them, but lower end computers can't handle them. A config option seems like the perfect solution.

When the config option is set to true, they don't generate anymore.

**Comment by purpleposeidon** [comment]
The vents in the antlion/gneiss dungeon thing also have this problem.

The actual problem is that vents spam particles regardless of how far away they are from the player; whatever mechanism spawns in the particle FX needs to check distance from the player.
