### ISSUE TITLE
Bone Shard -> Bonemeal is registered as a shaped recipe

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#311]
And so is the Caveman Club -> 6 Bonemeal recipe.

I think these should be registered as shapeless. It may not seem like much, but I'm fairly sure with some cross-mod stuff that could be annoying.

**Comment by ganymedes01** [comment]
Glad to see The Erebus is getting attention again :) Soon as I have time I'll join skype for a chat :3

**Comment by vadis365** [comment]
Missed you mate ;)
