### ISSUE TITLE
Sometime... We will make the big Bamboo Crate work better

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#312]
The current Bamboo Crate is in an odd spot... it's basically a really big chest, and I never really see it used much. I think that, if we decide to rework it, we should give it a scroll and search bar and make it work with automation and such. Though that could be complex as hell, I don't know. 

Hence, feedback needed.

**Comment by purpleposeidon** [comment]
You probably don't see it used much because nobody knows it exists. Tooltips? Old abandoned entomologist camp worldgen?

**Comment by Dylan4ever** [comment]
We may implement a guide book to the Erebus similar to the one Botania has.

**Comment by vadis365** [comment]
Needs fixing 1st from what I have read in #278 
Going to close until it works at a base level.
