### ISSUE TITLE
I want Umberpebbles :3

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#313]
Really simple. A block, affected by gravity, similar to gravel. 
Always drops itself, logically.

It cannot be found naturally (unless we want it to), but you can craft it using 1 Umbercobble and a pickaxe of any kind (the pickaxe loses 1 durability in the process). It is a shapeless recipe.

If possible, make it so that you can use this instead of Gravel in TCon recipes. I'd love to be able to create a smeltery when living in the Erebus.

Texture: umberPebbles
Folder: src/whatever/blocks

**Comment by ganymedes01** [comment]
Why is the Limbo folder empty?

**Comment by ganymedes01** [comment]
Lex complained? What lex? LexManos? iLexiconn? Some other Lex I haven't met yet?

**Comment by Dylan4ever** [comment]
Andre come online i explain pl0x gg.
