### ISSUE TITLE
Bio-veloxity and Supervelocity consuming tweaks

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#315]
The current situation, I believe, is that you rightclick them and you get a speed boost, which is a stronger one with the Super one.

So, how I'd like to see the new situation:
- Consuming the normal one gives you a 10 second Speed II buff. It is consumed in the process.
- Using the super one gives you the same boost for 5 secs. It is not consumed and can be used indefinitly.

The "consuming" should take half the time it normally takes to eat something.

That's it. Simple quality of life changes.

**Comment by Zsashas** [comment]
I actually thought it was a bug that it wasn't consumed when used, at first. This sounds like a better system.
