### ISSUE TITLE
Big Fat Long List of Weird/Buggy/Broken Things

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#317]
I went through the creative tabs to recall all the issues that I've found. Some things might be fixed already.

Altar Anything: What do these do? Uncraftable.
Antlion egg: Never seen one. Did find one of those ghostsand thingies a long time ago.
(Bamboo Extender: Don't recall if I've ever got this thing working...)
Gneiss Blocks: Wouldn't it be nice if silk touch made them not turn into lava?
Composter: What goes in the bottom slot?
Crafting Altar: Also not used?
Glowing Gem: What's this do?
(Honey/bees: Haven't gotten too deep into them yet; altho bees don't seem as interested in collecting nectar as they ought to be)
Lightning speed block: no crafting recipe. Judging by the effects of the lesser one, this is probably a good thing.
Mud: Too hard to break.
Mirbrick: too expensive? Maybe mud/mud bricks should work line vanilla clay/bricks.
(Mucus bomb: never tried it)
(Oferring altar: This is how you get the gaean keystone, right?)
Petrified wood: Texture's ugly.
Sap/Sapless Wood: Don't think I've ever found one.
Silos: I was able to deduce how the ants worked; however the tool slot in the ant GUI flickers very rapidly. Also I think I wasn't able to get one of the roles to work.
Tarantula egg: never found one.
Umberstone button: Does it stay on for a different amount of time than vanilla stone/wood buttons?
Volcanic diamond ore: never found any. Looks really cool tho. But there's no oreless version of the stone.
Wasp nest: never found any? Maaaybe one, but I wasn't able to properly investigate.

Bamboo: Impossible to grow. I've looked at the code for its overcomplicated growing rules, and still could not get it to grow.
Beetle larva: larva meat products give inconsistent confusion effects when eaten.
I get the impression that, given enough reloads, every namable mob becomes named.
Crimson/Other hearts: How on earth do you get these things? What do they do?
Glowshroom: never found them (Apparently fixed tho?)
(Gold/Other scarab Idols: Spawn in one of the big dungeons? haven't found a real one yet.)
(Supernatural velocity: ISTR finding at least one of these...)
(Umbergolem: Weird crafting thing; poked at it a little bit.)
Whetstone/whetstone powder: never found one/uncraftable; hence the newspaper is also uncraftable.

Augmented scorpion pincer/block extractor: The scorpion pincer's a bit rare
Rhino armor: totally badass
Ritual dagger: Does nothing?
Soul crystal: Does what? Uncraftable.
Tarantula boss trophy: Might have found in dungeon loot or something.
Wasp sword: Uncraftable/never found. Drops from the Hornet of Despair, perhaps? I've killed a couple of those however.
Woodlouse ball: Never found one.
Horn of the Swarm: Comes from where?

Bullrush/Droughted shrub/weeping blue bell/water flower: don't drop themselves when broken; can only be collected by bonemealing.
tile.erebus.waterFlower.name: neptunepink.bugreport.unlocalized.text

**Comment by vadis365** [comment]
OK I'll have a go at explaining some of this - lol
Altars are craftable with altar fragments and then activated with the wand of animation
4 types explained here : http://the-erebus.wikia.com/wiki/Altars

Antlion egg is a useless trophy that you get from beating the Big Antlion boss

Bamboo extender: https://www.youtube.com/watch?v=vhSMg6FE1X4

Gneiss Block - good idea :)

Composter uses mold as a fuel (collected with shears from the Fungal forest)

Crafting altar is due for removal as the magic system is being aborted

Glow gem is a nice light block that can be turned off and on with a right click  - can be place on any solid surface including ceilings and floors

Bees AI is a bit buggy and due for a major overhaul (I made them a very long time ago and could probably make them a lot better now :P )

Lightning speed block is made in the crafting altar (will be changed) - there is an NEI handler btw

Mud - sure, harvest level/speed can be changed

Mir brick - just some crap deco block with no real use

Mucus bomb - same as TNT but just causes knockback (repels mobs)

Offering altar - yes also has an NEI handler

Pertrified wood - yup, blame Dylan

Sap stuff - not sure about that - I think it should be in the jungle - due for removal anyhow.

Silo/Ants - hmmm... I'll check it out for the slot flicker thing - which Ant was lazy?

Tarantula Egg - useless trophy from beating the Brood Mother Tarantula boss

Umberstone button - I don't honestly know

Volcanic diamond ore- found under lava in the desert  - item drop will not burn in lava

Wasp nest - look up to the ceiling in jungles - they are quite common

Bamboo - @chylex is to blame for this - he went insane making it waaaay overcomplicated

Beetle larva - unclear what you mean by this...

Crimson/Other hearts - due for removal - magic system is going to be scrapped

Glowshroom - grow in the fungal forest - can be turned off in worldgen with config

Gold/Other scarab Idols - dropped from the umbergolem minibosses in the volcanic dessert maze - used to unlock the pyramid capstones...

Supernatural velocity - rare drop from centipedes and solifuges

Umbergolem - brought 'to life' by the wand of animation - will attack any nearby mobs 

Whetstone/whetstone powder - drop from woodlice - which only spawn from breaking hollow logs or rotten wood

Augmented scorpion pincer/block extractor - sure, I the the extractor is due for removal as well :(

Rhino armor - ty :P

Ritual dagger - due for removal (magic system crap again)

Soul crystal - dropped by Antlion Overlord (Boss mob) - used to craft wand of animation

Tarantula boss trophy - trophy from beating the Brood Mother Tarantula boss

Wasp sword - gained from breaking a wasp spawner found in wasp nest  (Look up in jungles)

Woodlouse ball - if you are fast enough - right click on a wood louse - you can pick it up and throw it at mobs

Horn of the Swarm - dungeon loot - will be changed as it is pretty useless

Double plants - yeah code got changed and never fixed - will do that.

tile.erebus.waterFlower.name: neptunepink.bugreport.unlocalized.text - lol

**Comment by purpleposeidon** [comment]
Altars -- Ah, a wiki! ...I don't see any links to it in the forum thread OP or on here.

NEI handlers -- I don't use NEI! >.>

Beetle larva -- One of them doesn't give confusion or something; I'll have to check.

Glowshroom growing in the fungal forest -- This is a new thing? I'll crop the dimension & explore it some more.

Whetstone/whetstone powder drop from woodlice -- That's a bit obscure

**Comment by Dylan4ever** [comment]
Honestly  I am to blame for this mod being so horribly obscure. I hope to start working on an in-game book sometime soonish.

Dave might as well remove Mirbrick... It's useless even for a deco block.

I made the petrified wood texture an incredibly long time ago, I should indeed overhaul it sometime.

The Erebus is in need of major rebalances and tweaking anyway, which we wl definitely work on.

I might even have the velocity blocks removed, too useless for their cost (I love messing with them in creative though).

Anyway, the Erebus is a total mess due to my bad managment and horrible ideas. I will better myself, I promise.

**Comment by Dylan4ever** [comment]
Umberstone button is literally just a button to blend in with Umberstone.

It might be better to remkve the supernatural velocity as well. What is its special use again? I dont even remember.
