### ISSUE TITLE
Put ranged equipment in tarantula miniboss chests

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#323]
Instead of swords & such. The indirect damage requirement is (7 stacks of tarantula paws, a full beacon, half a q-suite, and like 20 deaths) a bit non-obvious.

**Comment by Dylan4ever** [comment]
That is a solid idea... It's true that it is a bit vague how to kill the beast, there will be a proper way to read up on the bossfight in the future (by way of the Encyclopedia Erebus most likely).

**Comment by vadis365** [comment]
Read the wiki - it is incomplete but actually tells you stuff...
'The Encyclopedia Erebus' that Dylan has planned will probably never happen as he never actually bothered with the wiki in the first place...
