### ISSUE TITLE
I'm gone.

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#324]
It's been fun and all that but I don't agree with a lot of things Dylan wants to do and tbh it just isn't fun reworking all the code. Good luck with things and stay in contact. 
Dave.

**Comment by Dylan4ever** [comment]
Dave, I'd love to hear what exactly you disagree with. I believe most changes I proposed aren't drastic, it isn't even reworking all the code in the slightest. We will rework features that can be better and we will rewrite certain bits that need a recode to be able to function optimally, but I never talked about a recode.

I hope to see you on Skype.

**Comment by purpleposeidon** [comment]
:D
