### ISSUE TITLE
Add Scorched and Varnished Slabs

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#325]
''If you add the slabs in the future with the names "slabPlanksScorched" and "slabPlanksVarnished", the recipes will automatically start working.'' ~ Jaquadro, after he finished creating the ''Storage Drawers: Erebus Pack''

Can't hurt and helps for the compatibility (some of his recipes use slabs which aren't available for those).

**Comment by ganymedes01** [comment]
Should I do it the clean and organised way (breaks previous worlds) or the shoehorned way (keeps previous worlds)?

Also, worth reminding that way back when those were implemented they actually had the full suit of blocks, but *someone* asked for them to be removed =P

**Comment by vadis365** [comment]
Do these woods also make fences?

**Comment by vadis365** [comment]
shoehorned.

**Comment by vadis365** [comment]
closing because no new features should be added until the mod has been ported to a higher version.
1.9 will break any old worlds for the Erebus so this is now irrelevant to anything.
