### ISSUE TITLE
Biome ID not higher than 127

### ISSUE THREAD

**Issue by Dream-Master** [ganymedes01/TheErebus#327]
Please make it possible to can using the Ids to 256
I have Biome o plenty and other Biome mod that make it hard to find free Slots below 127. Thanks

**Comment by ganymedes01** [comment]
That's not just an arbitrary restriction that we came up with. Mojang coded biomes that way, there's nothing we can do about it.

**Comment by Dream-Master** [comment]
Why other mods exept Ids higher than 127. RWG or Biome o Plenty or RTG or Extra Biome XL ????

**Comment by SMEZ1234** [comment]
If you're having issues with biome IDs, why wouldn't you just assign those IDs that can be larger than 127 to over 127, and then use the new free slots for the IDs for the Erebus?

**Comment by Dream-Master** [comment]
Changing biomes on a existing map is not a good idea. I find some nether biomes from bop and change this and reset the nether. My question is only why all the other mods can use 256 ids and your mod not. I think the 128 Id thing is not a mine craft thing any more because mine craft set some biome variation on id over 128. I think only mc versions below 1.7. Have this problem. Anyway I fixed it for me but when you can change it to 256it would be nicer.
