### ISSUE TITLE
Gany - a question

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#329]
Would you be pissed off if I removed animation magic from the code instead of just disabling it?
I know you put a lot of work in to the system - but I don't think we will ever implement it.
There are quite a lot of classes involved and atm it just makes the dl bigger.
The code history will be stored on git, so if we ever do use it, it can be retrieved.

Please let me know mate :)

**Comment by ganymedes01** [comment]
Made a new branch, so feel free to delete it from master :)

**Comment by vadis365** [comment]
Thanks man.
