### ISSUE TITLE
More Tool Tips Needed

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#330]
Some of our blocks and items really need tool tips to explain what they are/do.
For example the bamboo crate -> colossal crate function is not obvious enough.

**Comment by trollworkout** [comment]
i have no idea what or how to use bamboo bridge and extender.

**Comment by vadis365** [comment]
Vaygrim made a nice video on the Bamboo extender:
https://www.youtube.com/watch?v=vhSMg6FE1X4

**Comment by trollworkout** [comment]
@vadis365  thanks ill check it out

**Comment by vadis365** [comment]
closing this because it is something I'm not ever going to get around to, probably....
