### ISSUE TITLE
Fire Brats are coming back too

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#331]
Will re-add fire brats as a dungeon only mob - they will have a chance to spawn if a player breaks a gneiss block

**Comment by trollworkout** [comment]
automagy or forbidden magic mod adds firebats to nether

**Comment by vadis365** [comment]
No, Firebrats with a 'b' - they were like silverfish but set you on fire...

**Comment by trollworkout** [comment]
@vadis365  ahaha :D nvm

**Comment by vadis365** [comment]
closing because no new features should be added until the mod has been ported to a higher version.
