### ISSUE TITLE
Biomes Generating in the Overworld, despite IDs properly assigned

### ISSUE THREAD

**Issue by Zsashas** [ganymedes01/TheErebus#333]
Ok so I read about how biomes look for IDs 128 above themselves for sub-biomes. I did a biome ID dump with NEI, and checked every ID I have, and they are all assigned properly. Erebus Biomes are only in pairs, so should never generate outside of the Erebus. However, they still are. Here is the biome ID dump so you can verify. The (aligned) version just makes the pairs easier to see.

Biome ID Dump: https://www.dropbox.com/sh/2pp2q8f6vpluqsp/AACOmaucSSbGlN1BiuDEOKYya?dl=0

I wasn't sure which file format would work, so here are both. I use LibreOffice (Calc) myself, and both open as spreadsheets as normal.

**Comment by Zsashas** [comment]
Also, it would seem like the biomes are not generating as sub-biomes in the overworld, but as full normal biomes on their own.

**Comment by vadis365** [comment]
This is due to a biome ID conflict, honestly. The Erebus code should only generate Erebus biomes in the Erebus. The only way it can happen is if you have an overlap in biome ID's with overworld biome ID's.
Closing as this really isn't a code issue.

**Comment by Zsashas** [comment]
I've made sure that the biomes are all separate, and none of the Erebus ones are 128 above an overworld one, or anything other than an Erebus biome.
