### ISSUE TITLE
Make Erebus Honey interchangeable with Forestry Honey

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#335]
We have similar items that could quite easily be oreDict the same as Forestry.
Our fluid is also registered under the same name.
Erebus -> Forestry
Honey Drip -> Honey Drop
Erebus Honey Fluid -> Forestry Honey Fluid
Bucket of Honey -> Honey Bucket

I propose a mod check for Forestry and defer our honey fluid and bucket placement of fluid to the Forestry fluid. If Forestry is not loaded then default to our honey. This all depends on if an API or some other magic exists.

Erebus Worker Bees are due for an updated AI, so this would seem like a good time to add some cross mod compatibility.

*Edit - Maybe this would be a good time for me to add the evaporation chamber for nectar and the centrifuge for cleaning honey?

**Comment by vadis365** [comment]
Forestry API handles Generator Fuels - so that is all good
https://github.com/ForestryMC/ForestryAPI/blob/master/forestry/api/fuels/FuelManager.java
The oreDict registry is also pretty comprehensive :)
https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/core/config/ForestryItem.java

**Comment by Nirek-K** [comment]
There are several ways you could go, one of the simplest being making a recipe in your machine/etc to make forestry honey drops out of yours, either alternately or instead of. Another option would be making a forestry centrifuge/still recipe to convert it that way.

**Comment by vadis365** [comment]
Closing this as Forestry is already way ahead in terms of compatibility. :)
https://github.com/ForestryMC/ForestryMC/issues/831
