### ISSUE TITLE
Wood Metadata can't be crafted into Planks

### ISSUE THREAD

**Issue by Vanir2314** [ganymedes01/TheErebus#337]
Version: 0.3a
Pack: For the Love of Adventure 1.2.10

I went into the Erebus and mined some wood, but wasn't able to craft it into Planks or throw it into an TE Sawmill. I later noticed I had two different Marshwood: 2352 and 2352:3. The one without meta can be used to get planks, the one with cannot. My rotten wood has the same issue (2349:3) but I have not yet found any without meta.
Is there a way to convert it?

Edit: Cut down a marchwood and it seems like the wood that spawns with all 6 sides bark texture (for example the roots) can't be turned into planks

**Comment by vadis365** [comment]
Fixed now - thanks for the report :)
Will all work in the next release.
