### ISSUE TITLE
Request: Config to disable Black Widows in the Nether

### ISSUE THREAD

**Issue by Zsashas** [ganymedes01/TheErebus#339]
As the title says. With just the Erebus, it's not much of an issue, but with additional mods that add mobs, the Nether gets dangerous really fast.

**Comment by vadis365** [comment]
I could do that.
Have you requested the same from all the other mods that are making the Nether dangerous for you?
Carry Milk, Anti Venom or Beetle Juice and Black Widows really aren't that dangerous.

**Comment by Zsashas** [comment]
The other mods already have configs for their nether mobs.

**Comment by vadis365** [comment]
Sure, I will do that for you. :)
Will be a config option in the next update.

**Comment by trollworkout** [comment]
i use a mod called Spawn Control 2 and I disabled it from spawning in the nether . I think the mobs are fantastic and very well done but they don't make sense in the nether.

**Comment by vadis365** [comment]
This is now done. Will be in the next release.
