### ISSUE TITLE
Crashing upon entering erebus for the first time

### ISSUE THREAD

**Issue by whitepyros** [ganymedes01/TheErebus#340]
First time i entered the erebus i was greeted with this crash
http://pastebin.com/4kd9YPj7

Attempting to load save again generates this crash
http://pastebin.com/PKQcVEuK

**Comment by vadis365** [comment]
Mariculture is actually causing that not The Erebus.
Black list The Erebus (default Dimension is 66) in the Mariculture config for the generation.
Also please report this bug to the Mariculture Git Hub.
This has been a long standing issue that hasn't been fixed by them.
