### ISSUE TITLE
suggestion: change titan stew naming and recipe

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#343]
Uncooked Titan Stew => Raw Titan Stew
Cooked Titan Stew => Titan Stew

change
pot + titan chop (or 2 beef) + carrot + potato + cabbage + ore:mushroom + ore:mushroom
(7 items looks ugly plus you can use any mushroom which may be odd to replace big ass dutch fingers with tiny brown mushroom)
TO
raw titan chop + carrot + potato+ cabbage + big mushroom (5 individual recipes for each of the big erebus mushrooms dutch fingers, dark capped mushroom, grandma's toes etc) + pot
(no more 2 beef, add container last similar to Minecraft mushroom stew, only erebus mushrooms can be used)

**Comment by vadis365** [comment]
I think the name and recipe are fine. you can probably use minetweaker to tailor the recipe to what you want.

**Comment by trollworkout** [comment]
i already did :) thanks.
