### ISSUE TITLE
add complete Thaumcraft aspect support (I have a script made if you need)

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#344]
just that.

I made a script using Minetweaker 3 + Modtweaker and manually added all the aspects myself to all the blocks/items/entities I could . I could share that with you so all you have to do is manually go trough and add them in so you don't have to make the effort of having to think what to add for each one. 

my script supports some the extended aspects like gluttony, famine, luxury, wrath etc

**Comment by ganymedes01** [comment]
I'd be willing to add support for the vanilla thaumcraft aspects (so no gluttony, famine and etc)
If you have the script please do share, but if it uses those aspects, I'd be more interested in just a list of which items aren't currently supported (or could better be supported)

**Comment by Zsashas** [comment]
Yes, please do share this script :D

**Comment by trollworkout** [comment]
@ganymedes01   @Zsashas 

hunger (fames) and want (lucrum) is actually part of original thaumcraft. 

envy (invidia) , greed (gula), wrath (ira), sloth (desidia), hell (infernum), lust/luxury (luxuria), pride (superbia)  are forbidden magic. 

here is the list for thaumcraft + forbidden magic aspects 
http://pastebin.com/DNL7nQ03

note that this is based on the creative tab  so most of the things listed there should have aspects. but i did notice a few things like multiple entities or plants that are unlisted in creative . i have added aspects for those as well but there may be others that i am not aware of.

**Comment by vadis365** [comment]
closing because no new features should be added until the mod has been ported to a higher version.
