### ISSUE TITLE
minor but important fix: change bee talisman from ore:goldNugget to  minecraft:goldNugget

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#345]
it adds some odd interactions with other mods for example you can build the talisman out of coins

**Comment by vadis365** [comment]
It uses a gold nugget - I don't see this as a problem.
Any changes to the recipe are done with the ore dict from other mods.

**Comment by trollworkout** [comment]
ok that's fair . i guess is more of a cosmetic thing.
