### ISSUE TITLE
4 mushroom hide -> 1 leather (similar to rabbit hide to leather in 1.8+)

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#346]
just that.

**Comment by vadis365** [comment]
Not a bad idea - but is there a real use for it?

**Comment by trollworkout** [comment]
dunno. you decide :)

**Comment by trollworkout** [comment]
i find it useful because you cannot easily get leather in erebus. if you make a base there you have to keep going to overworld for leather or get cows in erebus.

**Comment by vadis365** [comment]
If it is for books, exo plate can be used as an alternative. OR use this instead of going through the portal and running around. I do. it makes things so much easier :P (Shameless Plug for another mod).
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2236752-transport-terminals-tech-based-teleportation-1-7

**Comment by trollworkout** [comment]
: ) exo plate can be used for books you are correct. but there are a few other things you use leather for even and you may wanna use in erebus . up to you . i find it a good thing to maximize the usefulness of all items in the game.

**Comment by vadis365** [comment]
I can add the recipe no problem. I'm just not sure it is actually that useful, as nothing in The Erebus actually uses leather and other mods can be used to 'tweak' recipes for individual users needs.

**Comment by vadis365** [comment]
I'll leave this issue open for now and make it a low priority. Once some of the already planned things are done we can always come back to this and see about adding it. Thanks for the idea.

**Comment by trollworkout** [comment]
np. you guys call the shots. i added it in my minetweaker 3 setting and i found it quite useful cause it makes a lot of recipes available in erebus while still being quite rare.
