### ISSUE TITLE
add bamboo to ore:bamboo oredict

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#347]
seems bamboo is an odd one .there are a couple of mods that have bamboo added but none of them are compatible with each other. making bamboo oredict increases the chances of compatiblity with other bamboo mods.

**Comment by vadis365** [comment]
Requested Growthcraft team's oreDict info on bamboo - hopefully we can ge it compat ;)
https://github.com/Alatyami/Growthcraft-1.7/issues/125

**Comment by trollworkout** [comment]
@vadis365  nice . i like this. both of these mods are pretty badass. 

their bamboo seems to be much more useful since they added their bamboo to oreStick or something and can be used in place of sticks. kinda cool. i'd even request to have your bamboo be their bamboo + your custom items when growthcraft is installed. optional in the config. i deff love the extender and bridge and nerdpole. that shit's dope as hell. 

you should test it out they got a lot of cool ideas for bamboo. even bamboo scaffold like a ladder block. very handy.

**Comment by vadis365** [comment]
nerp. oreDictionary is they way we will integrate.

**Comment by purpleposeidon** [comment]
Grwothcraft's bamboo item uses "stickWood", "woodStick", and "bamboo".

**Comment by trollworkout** [comment]
@vadis365  aight :)

**Comment by ganymedes01** [comment]
Our bamboo planks are already registered under "planksWood". What else are we to register them as?

"woodPlanks" is just silly, I'm not registering anything under that name =P

**Comment by ganymedes01** [comment]
Our bamboo is already edible (if you turn it into soup)
All of the other bamboo items are already registered in the ore dictionary.
