### ISSUE TITLE
suggestion: change or expand the portal - only humanoid mobs can be moved between dimensions

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#349]
due to the way the new portal is built mobs cannot be moved from one dimension to the other. most erebus bugs are 2 - 4 blocks wide making it impossible to move bugs to overworld and many animals from overworld are 2 blocks long making it very hard if not impossible to move to erebus. 

the portal only allows 1 - 2 blocks high and 1 block wide mobs. so hobgoblins or humanoid or dwarves or the player(s) can go trough easily. 

i would like to be able to move creatures back and forth trough the portal especially the ones i can farm for resource.

maybe the change was intentional so no bugs can leave erebus. i don't know. you guys decide.

**Comment by purpleposeidon** [comment]
I'd definitely like an Erebus-way to transfer bugs.

**Comment by vadis365** [comment]
Golden Lasso? Safari Net? Lots of other mods do it.
I did make an Amber block launcher in 1.6.2 that captured Erebus mobs and preserved them in blocks.
When broken it spawned the entity again. It also displayed the mob in the block so it could be a trophy. Unfortunately this was never implemented and I'm not sure if I still have the SRC for it.

**Comment by vadis365** [comment]
Closing this issue for now as other mods allow for mob transportation - will revisit in a later update and see if we can re-make the amber block preservation mechanic ;)

**Comment by trollworkout** [comment]
im using forbidden magic and luckily it allows the creation of limited spawners for all non bosses :)
