### ISSUE TITLE
erebus block o bones doesn't save thaumcraft baubles  currently wearing

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#352]
just a  request to support baubles inventory saving in block o bones that's it.

**Comment by ganymedes01** [comment]
We won't be adding support for other mod's extra inventories atm.
Each mod handles extra inventories in a different way, it becomes a pain to keep track of all of them. Sorry.

**Comment by Zsashas** [comment]
At the very least, have them drop on the ground. As it currently is, the items are destroyed completely.

**Comment by vadis365** [comment]
This really isn't our fault - I know for a fact that other mods that add graves have issues with baubles and tinker's extra inventories. Tinker's have recently updated the way their drops happen on death which may or may not solve it this end - but I'm really not sure about baubles drops.
The way our Block o' Bones works is to take the vanilla inventory and armour and add it to the block o' bones it also scans the area around the player and adds any loose items to it's inventory. The Forge event that causes the bones to drop is set to LOWEST which means it should happen late after player's death. There is nothing in our code that should stop any other mod's items from dropping on the ground - in which case if it happened before our bone block is placed the items would be added to it's inventory. We have no say in how another mod handles it's drops and have tried to make our grave marker as compatible as we can.

**Comment by trollworkout** [comment]
@vadis365  im pretty sure other mod's inventories drop on death like normal.

this can easily be fixed by either implementing a second step or replacing the code to absorb all dropped items in the area of death. i think death chests mod does that and take all inventories from all other mods. even if there are random stuff u didn't have is fine. better than losing your precious items.

**Comment by Zsashas** [comment]
I know that OpenBlocks graves work well. Maybe ask them how they did it?

**Comment by vadis365** [comment]
@trollworkout read the comment I made above yours - that is EXACTLY what we do.

**Comment by trollworkout** [comment]
@vadis365  ah ok..i thought you said you scan for things in inventory then add those to block of bones not just everything that dropped : )

**Comment by vadis365** [comment]
@Zsashas - that is not entirely true lots of mods have problems with other mod's inventories.
Each mod that adds extra inventories code things differently. It is pretty much impossible to cater to every mod's different systems. I will have a look as to why other mods are not dropping their inventories but we will not be adding any 'special case' code to deal with other mod's.
The way we have it at the moment will work if other mods drop their stuff.
Some other mods have added compatibility for other mods like Glalacticraft etc. and there are 'workarounds' but no one way will work for all mods atm.

Just a couple of links that I have found off the bat to show you I'm not making stuff up :)
https://github.com/OpenMods/OpenBlocks/issues/694
http://ftb.gamepedia.com/Grave
https://github.com/Azanor/Baubles/issues/90

**Comment by vadis365** [comment]
@trollworkout  - We do do both. We get the vanilla inventories and store them to the block and then the block scans the area in a radius for any loose items and then adds them to the block. What we are trying to get to the bottom of is why other mods' items are not dropping as they should with the block of bones enabled. This is stopping the block from 'finding' the items on the ground and storing them.
