### ISSUE TITLE
Crash when viewing creative menu

### ISSUE THREAD

**Issue by fishmealx** [ganymedes01/TheErebus#353]
I can't get anything to show up in the crash logs related to Erebus, but whenever I have Erebus installed I crash when trying to view the creative inventory (clicking the compass) or scrolling through the pages using the arrows. It happens to others as well, so far just on single player.

**Comment by vadis365** [comment]
Do you have Thermal Dynamics installed?

**Comment by vadis365** [comment]
Closing as there is a config in TD to prevent the error.
