### ISSUE TITLE
eating cabbage crashe the game

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#357]
you need a crash log?

**Comment by Dylan4ever** [comment]
Ofcourse we do.

**Comment by trollworkout** [comment]
okay . 
http://pastebin.com/SY89dG6Q

**Comment by vadis365** [comment]
Had this report before and I couldn't duplicate it - I'll look in to it.

**Comment by trollworkout** [comment]
is a null something. seems it crashes when i leak gas (aka fart). it works i made some sound then im about to do something maybe butt gas particles ?? i dont see any. just  crash some function is null pointer .

**Comment by trollworkout** [comment]
@vadis365  @Dylan4ever  just an update on this issue. seems this crash is occasional as i can't get it to replicate and i have no idea what triggers it. the crash does happen once in a while but i just cant figure out why.

**Comment by ganymedes01** [comment]
Fixed by accident in one of my re-writes
