### ISSUE TITLE
Umberpebble crafting please

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#358]
''you can craft it using 1 Umbercobble and a pickaxe of any kind (the pickaxe loses 1 durability in the process). It is a shapeless recipe.''

#313

**Comment by ganymedes01** [comment]
As I explained on skype back then... not possible.

**Comment by ganymedes01** [comment]
Closing due to lack of response for nearly a week

**Comment by Dylan4ever** [comment]
My bad. Can we just make it have a pickaxe in the crafting recipe but not take durability then?

**Comment by ganymedes01** [comment]
But then it will use up the pickaxe...

**Comment by vadis365** [comment]
skype?
