### ISSUE TITLE
Mob drops - Regarding ''rewards''

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#359]
So, I noticed the following mobs don't always drop something, which can feel unrewarding:

- The big mushroom hulk. I defeated him but got nothing in return.
- Beetles need to drop at least 1 Exoskeleton.
- Glowworm at least one bioluminesceneses.

Please :D? I'd change it myself since I know where to find the code for it but I'm afraid I'd mess something up >.>.

**Comment by vadis365** [comment]
Everything drops something - it all works OK for me.
Are you sure it isn't another mod causing this?
Closing because I don't believe this is an actual issue :P
