### ISSUE TITLE
More config options for the glowing mushrooms

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#361]
- Try and make it customizable how quickly it grows if possible.
- Also add a config option to just completely turn it off if necessary (setting it to 0 would do this already i suppose, i dunno).

This is needed. I'm leaving close to a mushroom biome and sometimes I have unbearable lag spikes.

**Comment by vadis365** [comment]
The glowshrooms already have a a config to turn them off.
Use it if you have troubles.

**Comment by Dylan4ever** [comment]
I have it off, but doesn't that only work for /generating/ them?

**Comment by purpleposeidon** [comment]
Are you sure it's the mushrooms? The glowing bugs are also fairly laggy.

**Comment by vadis365** [comment]
iirc @purpleposeidon added config options to turn off glowing mobs ;)
