### ISSUE TITLE
Is it just me or do Beetles need 2 Turnips before they can breed?

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#364]
Seems that way in my game... Anyway, if that isn't the case, please fix them still being able to be fed after they are already in breeding mode. Missclicking leads to a waste of resources.

**Comment by vadis365** [comment]
Just you. The feeding after bred is a vanilla mechanic - other mobs do that too.
I would suggest that you stop spamming the button. Not changing this. :P
