### ISSUE TITLE
Rotten Wood 208:3

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#365]
For some reason, I have a lot of Rotten Wood with metadata 3. This cannot be used for anything. Not sure why it does what it does. Could someone perhaps look into it?

**Comment by vadis365** [comment]
I fixed this.
It is the roots.
Compile a new Erebus or get a sodding workspace going.

**Comment by vadis365** [comment]
Download the zip from git, unpack it.
On the folder open a cmd window (hold shift and right click the folder).
type:
gradlew build
in the cmd window.
once it has compiled look for the Erebus.jar in one of the folders.
Then get back to me with some more up to date things or alternatively read the git commit history and look at what is fixed :P
