### ISSUE TITLE
Bugged recipe for Anti-venom Bambucket

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#368]
Dupe bug. You get both the Anti-venom Bambucket AND it returns an empty Bambucket. It shouldn't give the empty Bambucket back.

**Comment by ganymedes01** [comment]
Nothing we can do about that. We'll need a different recipe or a different way to craft it.
Perhaps using the altar?

**Comment by vadis365** [comment]
Confirmed this bug also returns a vanilla bucket if one is used.

**Comment by ganymedes01** [comment]
It's not a bug, it's the way the crafting works. it returns the container of whatever items were in the crafting table.
Hence my previous comment. We need to come up with either a different recipe or a different way to craft it that doesn't use the crafting grid

**Comment by ganymedes01** [comment]
Craft them in the smoothie maker from now on

**Comment by Dylan4ever** [comment]
Anti-venom in the smoothie maker kinda makes sense, I like it.
