### ISSUE TITLE
suggestion: bambucket sounds like a great idea but in practice is not that useful

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#373]
bambucket seems to crash all other mods that use buckets 
& are missing all other mod's liquids.

you could probably use reflection or some other java magic to generate other liquid bambucket but might not work like all other custom mod buckets. 

while is a great idea, i suggest you disable it altogether. 

i am using minetweaker 3 to disable it increase stability in my personal modpack.

**Comment by Dylan4ever** [comment]
Not having the other mod's liquids is intentional: while we could add oil and such, molten metals and such would not thematically fit inside a bambucket. Please give us a crash report or 2 for the crashes you get with other mods' liquids so we can look into fixing them.

**Comment by trollworkout** [comment]
i know but is pointless building a bambucket since u cant use it for anything other than 2 erebus recipes which have a regular bucket recipes anyway.

**Comment by trollworkout** [comment]
@Dylan4ever  i will give you a crash report 4 growthcraft seems to be crashing when i use a water bambucket on a barrel. ironically it does add water into the barrel when i reload the game. i will trigger a crash right now. brb.

**Comment by trollworkout** [comment]
here u go http://pastebin.com/F3sEfgzW

water bambucket + growthcraft barrel . i can try other mod blocks/mechanisms that use water like cauldron but i am afraid same thing will happen with all of them.

**Comment by trollworkout** [comment]
regardless. 

if i have a liquid i cannot pick up with a bambucket that i can pick with a bucket then what's a bucket if not contains liquids. is pointless building one ever since it can only hold 4 liquids.

as i said. sounds cool in theory but in practice is practically useless :( i never build one and is disabled in my modpack since you cant use it for anything.

**Comment by Dylan4ever** [comment]
The use of the Bambucket is not to provide another Bucket. It is to provide a low-economy alternative for moving some basic liquids and milking creatures, all while being stackable (Bambuckets are 1-use-only). This solves the problem of, for example, water being annoying to carry around multiples of since they don't stack. The classic bucket is meant to outclass the Bambucket in all ways since it is much more expensive.

We will try and make it work with othermodly containers ofcourse.

**Comment by trollworkout** [comment]
@Dylan4ever  if you can find a use for it like a nieche thing that only bambucket can do then by all means. is just needs to have a point. that's all im saying. 

by no means i am bitching about what is there. i am just trying to be critical but also helpful.  

i was loooking online and seems people dont build buckets from bamboo but more from wood. they build these bamboo water jugs from cut big bamboo however in pairs of 2 on a stick on the shoulders. maybe u can make bambucket carry less but be stackable in 16s  and using a stack of bambuckets consumes 2 at a time kinda useful for water cause u can stack up a 8 regular buckets . i'd even disable all other bambuckets and keep it water only.

**Comment by trollworkout** [comment]
@Dylan4ever  water bambucket crash has been fixed on growthcraft side by icedragon200
