### ISSUE TITLE
tweak: nerdpole crafting recipe is xSx,xBx,xBx should be S,B,B

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#374]
what i mean is you defined the recipe as
null, slime, null
null , bamboo, null
null, bamboo, null

GameRegistry.addRecipe(new ItemStack(bambooPole),
    " S ",
    " B "
    " B ",
    'S',slimeball, 'B', bamboo);
note the space 

instead define it as
slime
bamboo
bambo

GameRegistry.addRecipe(new ItemStack(bambooPole),
    "S",
    "B"
    "B",
    'S',slimeball, 'B', bamboo);

this way it can be crafted vertically anywhere

i'd even make it shapeless so you can craft nerdpoles on the go

**Comment by Dylan4ever** [comment]
Good ideas, will forward them to Dave and see what he thinks about it.
