### ISSUE TITLE
Composter - New recipes

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#377]
4 Seeds (wheat seeds/hanger seeds) -> 1 Compost
2 Seeds (any other type, such as melon and pumpkin) -> 1 Compost
2 Berries/Cacao -> 1 Compost
1 berry bush -> 2 Compost
1 Sugar Cane -> 1 Compost

I'd like to hear what other recipes there are, please :D.

**Comment by vadis365** [comment]
Not sure if the composter recipe handler has a variable stacksize output I can look but @ganymedes01 is the master of itemstacks here ;)

**Comment by vadis365** [comment]
not necessary for the time being but we may re-visit.
