### ISSUE TITLE
CrossModProblem with TConstruct and Iguana Tinker Tweaks

### ISSUE THREAD

**Issue by BakermanLP** [ganymedes01/TheErebus#380]
Hello,

I am having a little problem. Iguana Tinker Tweaks and TConstuct allow to repair their tools in a normal crafting grid, if this ist configured. But when I also load TheErebus mod, then this feature doesn't work. When I remove the mod after that, everything works fine.

User mods:
- forge 1492
- CodeChickenCore-1.7.10-1.0.7.47-universal.jar
- CoFHCore-[1.7.10]3.0.3-303.jar
- ExtraTiC-1.7.10-1.4.5.jar
- IguanaTinkerTweaks-1.7.10-2.1.5.148.jar
- InventoryTweaks-1.59-dev-152.jar
- Mantle-1.7.10-0.3.2a.jar
- Metallurgy-1.7.10-4.0.8.97.jar
- MetallurgyCore-1.7.10-4.0.4.18.jar
- neiaddons-1.12.14.40-mc1.7.10.jar
- NEIIntegration-MC1.7.10-1.0.13.jar
- NotEnoughItems-1.7.10-1.0.5.118-universal.jar
- TConstruct-1.7.10-1.8.7.build985.jar
- TheErebus-0.3a.jar
- TiCTooltips-mc1.7.10-1.2.5.jar
- Waila-1.5.10_1.7.10.jar
- Wawla-1.3.1-1.7.10.jar

I also tried to compile out of the github sources, but the result is the same.

Michael (aka BakermanLP)

**Comment by vadis365** [comment]
The Erebus shouldn't change anything to do with how crafting is done in any other mod.
This is a strange thing indeed. We honestly don't do anything funky with crafting which would cause this. The only thing we do add is crafting recipes/handlers for some Erebus specific blocks - but they are only used with our blocks and would only work on them. We also add a petrified wood crafting bench that acts exactly like a standard crafting bench, but I don't think this would cause your problem either.

**Comment by ganymedes01** [comment]
I remember hearing about this a while back. But I can't remember if we ever found out what was causing the issue XD

**Comment by BakermanLP** [comment]
It is relativ simple to get to this error. Only install Tinkers Construct, Iguana Tinker Tweaks + NEI. This combination is working. After that install TheErebus and then it doesn't work. I don't have any possibilities to track this down further. Sorry.

**Comment by ganymedes01** [comment]
So, I decided to finally get off my butt and try to reproduce this issue.. again.
And again I have failed.

Made a pickaxe with a stone head and wood for the rest, mined a few stone, and then placed it in the middle slot of a crafting station with some cobble around it. The result is a fixed pickaxe.
Works the same regardless of whether the Erebus is installed.

What I did notice was that I couldn't fix it in the 2x2 crafting grid, nor could I fix it if the pickaxe wasn't in the middle slot of the 3x3 grid. But that "issue" was present even when the Erebus wasn't.

**Comment by Renadarain** [comment]
Can this be reopened?  I can confirm that this is still an issue.

In Iguana Tweaks this option is enabled:
    # Allows to repair your tool in a crafting grid, without tool station [default: true]
    B:easyToolRepair=true

This works as designed without The Erebus installed but as soon as Erebus is back on you can no longer use the 2x2 crafting grid and repair things on the fly.

You are correct that you can repair tools in a craft table providing the item is placed in the centre slot (doesn't matter when you remove The Erebus).

The other thing that I'm noticing is that Auto Repair on Tinkers tools doesn't appear to be working with Erebus installed.

Hope this helps to track things down. :)

Regards,
Pickety
