### ISSUE TITLE
Weeping Blue, Firebloom (possible others? Sundew?) dropping bug

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#381]
They don't drop properly. Sometimes I don't even get anything, and it seems really random. Not sure if it's a bug or intended. Need feedback.

**Comment by Dylan4ever** [comment]
Can confirm for the Bullrush as well. Destroyed 5. Got 3 Papyrus. This needs to be changed.

**Comment by vadis365** [comment]
intended.
