### ISSUE TITLE
Maybe tone down the amount of Nectar you get a bit

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#382]
Because ho-ly-damn. I am getting sooooo much honey. No idea about conversion rates (to Forestry for example), but it seems like it goes way too quickly. Oh well.

**Comment by vadis365** [comment]
I just amped it because there wasn't enough to generate a decent amount to power forestry engines after the huge amount of processing needed - I can put it back tho'

**Comment by Dylan4ever** [comment]
Keep it at a value you deem alright. Maybe up the conversion rates a bit if needed, since there is such a huge abundancy of it that you are basically set for life once you set it up. This isn't necessarily bad, but you actually get more than you need in non-forestry worlds.

Or config options to set the rate at which you get it. That's cool too. Everyone loves configs.
