### ISSUE TITLE
Permanent buffs using the eggs you get from the bosses

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#383]
So I had this idea... What if you can get some permanent gamechanging buffs by using the Egg and a few other components in the Smoothie machine? 

I think this would be interesting. Here are 2 example: 
- Brood Mother buff. Nearby tarantulas are not hostile to you anymore. Furthermore, when you get attacked by another hostile mob, they attack those for you. However, the tarantulas spawned in the dungeon do stay hostile, otherwise it'd be too easy.
- Sandwalker buff. You can ''swim'' through sand, and while you are in the sand, you see mobs (an outline of them) through the ground and walls and such. The swimming goes decently quick. You need to press a certain keybind to sink into it.

These are just random ideas... They seemed thematic, but I'm not sure how complex they'd be to accomplish.

**Comment by vadis365** [comment]
Quite complex. Won't be done for a long while if it does get added :P

**Comment by Dylan4ever** [comment]
I know, just spouting :D.

**Comment by vadis365** [comment]
Closing because, well, errr... I can :P
