### ISSUE TITLE
This balance is needed for the tarantula dungeon

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#384]
- Babies health 15 -> 10. This way you can oneshot them if you are aptly prepared.
- Cooldown for the egg shot could be a bit longer. Not sure on this one.
- Spawners spawn one tarantula for each nearby enemy player. This way the difficulty scales with amount of players, which is good for SMP.

**Comment by Dylan4ever** [comment]
Also, did I issue the "babies not dropping anything" yet? Anyway, they need to drop a tiny bit of experience and nothing else.

**Comment by Dylan4ever** [comment]
The brood mother should only awaken when you attack her by the way. If its possible, also hide het health bar until she is attacked.

**Comment by vadis365** [comment]
I'll tweak some bits - the boss bar should stay though - it alerts the player to the dungeon.

**Comment by Dylan4ever** [comment]
Yeah true, but it isn't there for the antlion dungeon... ''Consistency''. Doesn't matter though. The aggro should only start when you attack her though.

Also, maybe make her invulnerable by arrows when her blue shield is down?
