### ISSUE TITLE
Cultivated recipes are actually way too expensive

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#389]
4 Supernatural Velocity? The amount of grinding you'd have to do to get that is... Ridiculous. A bit too expensive, I'd say. Shall we change it to the regular Velocity item and see how that goes balance-wise?  I mean, isn't supernatural velocity a rare drop?

We could also make (the big) Solifuges have, say, a 25% drop rate for them or something to fix this. They live in a dangerous area and are dangerous to take on, so this would gate that fairly nicely I feel. 

Looking forward to hearing what you think.

**Comment by vadis365** [comment]
The recipe is supposed to be expensive as once you grow it  - it grows by itself at a very fast rate.
I don't see a problem with making this hard to get.
