### ISSUE TITLE
Book hardcoded

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/TheErebus#399]
@ganymedes01 :smile:

**Comment by ganymedes01** [comment]
Not quite sure how to make the book translatable. Do you know how? D=

**Comment by vadis365** [comment]
would involve moving each page in to the lang (or similar) and getting it from there I guess :(

**Comment by vadis365** [comment]
@ganymedes01 did add an NEI handler for the smoothie block - but the book helps with knowing what each smoothie does...

**Comment by vadis365** [comment]
maybe we add icon's for the items and limit the text - so it could be lang'd?

**Comment by ganymedes01** [comment]
What if we got rid of the book and added tooltips to each smoothie saying what it does?
Seems more practical...

**Comment by vadis365** [comment]
sure, anything that is easier is better - I would like the book to stay (maybe English only :P )

**Comment by vadis365** [comment]
if we leave the book in for now and make tooltips for our non-English speaking friends, I will look in to a way to make the book translatable (Dan has done it in HEE).

**Comment by ganymedes01** [comment]
Added the word "Smoothie" to the end of every smoothie item to make it easier to search for them in NEI.
Removed the smoothie book completely.
Effects are now displayed in the tooltip:
<img width="345" alt="screen shot 2015-10-26 at 15 31 08" src="https://cloud.githubusercontent.com/assets/5294529/10733420/a2f20df4-7bf6-11e5-99ed-adf65ae15cc2.png">

**Comment by vadis365** [comment]
That's awesome and all that :)
What about people without NEI - how will they know the recipes?
Our wiki doesn't contain any information about this block or items it produces...

**Comment by Adaptivity** [comment]
@vadis365 I don't think that there are people around exist who plays modded MC without NEI... Well, if they are exist there are not much of them.
