### ISSUE TITLE
Chat messages hardcoded

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/TheErebus#400]
:(
1) AltarBase.java
2) ErebusCommandDebug.java

**Comment by ganymedes01** [comment]
I got rid of the altar messages
And the erebus debug command is meant to be used mostly by the dev team, so is there really the need to localise it?

**Comment by Adaptivity** [comment]
Since these commands available for everyone, yes they should be localized.

**Comment by Adaptivity** [comment]
@ganymedes01 still waiting for that so I can update ru_RU.lang :smile:

**Comment by Adaptivity** [comment]
/erebus gen <type> <feature> can be localized too I guess. Since type and feature words can be translated. Also, you added command.erebus.mobcount in the .lang file but didn't changed the line in the code.

**Comment by ganymedes01** [comment]
Oh right, I tried to translate that line but it didn't really work. I'm still not sure how localising commands works to be honest with you =P

"/erebus gen type feature" was an oversight. I'll add that :3
