### ISSUE TITLE
Portal Concept

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#402]
![Leaf Portals](https://cloud.githubusercontent.com/assets/150333/10745201/e4bfeb9c-7bfc-11e5-84a0-bc6d58bffa05.png)

1. Place down the Gaean Keystone.
2. Nearby build a ring-ish shape of solid blocks.
3. Fill it with leaves
4. Click the keystone with the staff. The staff goes into the keystone.
5. The leaves are replaced with portal blocks, maybe with a bit of animation.

The Gaean Keystone renders the Staff instead of the beacon, 'cause the beacon's kind of annoying (at least in the Overworld).

Rules for erebus portal blocks are more relaxed than vanilla's:
* Must have at least 1 portal block neighbor.
* Each portal-neighbor must have either a solid block or another portal block on the opposite side
* All neighbors must be in the same plane

(These rules allow flat portals and fancy portals, but also naked skinny portals and 3D pipe portals.)

Creating the portal searches in an 8 block radius for a contiguous set of leaves that all obey the portal-block rules. The maximum size of a portal is 81 blocks.

Stepping through the portal places you on top of the keystone on the other side. If the destination is the overworld, then a portal is not created, but it does try to find a keystone.

On the erebus-side, if a keystone is not found, then a standard portal layout is placed: a 3x3 hollow area, where the portal blocks would go, surrounded by umbertiles, with a 5x5x5 clearing in front of the portal w/ a umberstone floor if necessary, and an empty keystone on the floor.

Assaulting the keystone removes the staff. The staff will remain in the keystone if the portal is broken by some external means.

When the staff is removed or a keystone with a staff is broken, the nearest portal block is broken, and the the block update cascades to close the portal.

The keystone probably emits particles towards the portal blocks.

On the overworld side of the portal, bugs that can spawn in the biome of the destination probably leak out occasionally.

**Comment by vadis365** [comment]
Sounds really good. Make a PR and we'll add it :P
