### ISSUE TITLE
Death Compass

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#409]
Pretty easy. On player death when you re-spawn a  written book is added to your inventory with the location you died at (where your block o' bones is) X, Y, Z. Could be done easily with a player event. There is a legit reason for this, as a player has died on my server and he has no idea where his block o' bones is or where he actually died - possibly 1000's of blocks away from his spawn point.
Not OP as the player will still have to go get their stuff back. Maybe the book could be 'consumed' after 1use. That way a new book can be issued each time.
*Edit an alternative would be to print a chat message out that can be F2'd :P

**Comment by ganymedes01** [comment]
I like it.
Get your perky butt on skype

**Comment by ganymedes01** [comment]
How about a Death Homing Beecon instead? It's more "immersive" and just as effective :3

**Comment by vadis365** [comment]
I have made a whole new texture for this item. The item will be based on the basic Homing beecon, it will however, not be programmable and useless once the player has recovered their stuff. What about allowing it to be crafted in to something after it's usefulness is over? I propose something pretty useless like 1 bonemeal for shits and giggles...

**Comment by ganymedes01** [comment]
A random wooden tool ;D

**Comment by vadis365** [comment]
done all bar the disposable crafting.
