### ISSUE TITLE
Should mold create rotten logs?

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#410]
Rotten logs don't seem to be renewable.

It seems reasonable to me for mold to grow by converting non-rotten logs, but that might make mold farms too expensive.

**Comment by vadis365** [comment]
hmmm... I already added cultivated mould /moss that can only grow on rotten logs.
With a quick tweak I could make it so it can only grow on normal log that change to rotten logs.

**Comment by ganymedes01** [comment]
Make it grow on rotten logs AND normal logs :3

**Comment by vadis365** [comment]
I'm going to leave this for a while just to see how the new mould/moss blocks fare in tests.
Rotten logs are not particularly important for anything, so as a renewable resource they can be foraged for in the biomes they gen in. I may revisit if the cultivated wall plants need tweaking.
