### ISSUE TITLE
Worker Bee AI is due for a major re-work

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#418]
This will require quite a major re-work of the mob code so it will be made in a separate update along with other bee related things (including more honey functionality, Queen bee mob and possibly the start of the 'hive' dungeon plan.)

Main Worker bee problems:
Bees get stuck under things all the time - The pathing AI needs a complete overhaul.
Bees tend to suffocate or take damage from getting stuck resulting in eventual death.
The AI tends to bug out and not update or work as intended (lazy bees).

More possible functions:
Bees could be used as transport couriers involving moving and collecting items to inventories.
For example they could collect from an Ant Silo and deliver produce else where.
Queen Bee already has planned functionality (not for this issue).

**Comment by purpleposeidon** [comment]
Is it intended to be able to just lock bees in a box with a stigma floor + honeycomb chest?

**Comment by vadis365** [comment]
I'll remove the ability to silk touch the stigma in the next release - just to stop this cruel practice you are partaking in :P

**Comment by purpleposeidon** [comment]
:[ But it was only on a creative world...

**Comment by vadis365** [comment]
Closing this - I will have to re-do most mob AI's whilst updating to 1.9 so no need for this issue.
