### ISSUE TITLE
Cicadas don't despawn and still attack players even on peaceful mode

### ISSUE THREAD

**Issue by ganymedes01** [ganymedes01/TheErebus#422]
They could also do with a texture that isn't just plain green ;D

**Comment by vadis365** [comment]
The Peaceful thing is an easy fix but I'm not sure what you mean about not dying. They are classed as a passive mob. They don't actually cause any damage just defensive knock-back and potion effects if you get near. Do you mean they should de-spawn if the player is in peaceful mode?

**Comment by ganymedes01** [comment]
by "dying" I meant "despawn" yeah.

The effects aren't just deffensive from what I could tell, just by going near them I was getting shot with blindness and nausea. Which is fine for a non-peaceful world...
But I think "peaceful" inplies that mobs won't do anything harmful to you at all, that includes negative potion effects

**Comment by vadis365** [comment]
Sure - the de-spawn option is simpler to implement - so I'll do that ;)
They need a tweek on their drops anyway to include the 'recentlyHit' boolean as repellent seems to be dropped all over the place - same with mosquitos, blood snails and leeches from my testing.
