### ISSUE TITLE
some ideas for Erebus Achievements & thanks for making them work

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#427]
Thanks for your work guys. I was reading the github closed issues + changelong seems  you have  fixed a lot of issues one of which being the Erebus Achievements now actually work :)

Here are a couple of new ideas for you. I organized them in a bit of an order

A secret below the world (arrive in Erebus)
* Cockroach Safari *Hunt some local wildlife* (kill any 1 Erebus mob)
 *  Don't wear them out *Craft an exoskeleton armor piece* (craft any 1 exoskeleton armor piece)
    * Do wear them out *Upgrade your armor to reinforced exoskeleton plate* (craft any 1 reinforced exoskeleton plate armor) 
      * Up she goes... Up she goes... *Craft a glider armor*
        *  I'm flying, Jack! *craft a powered glider armor*
    * Beetle Raider *craft a bettle riding kit* 
    * Powerfist *Craft an augmented scorpion pincer*
 * Rhino what? *Kill a rhino bettle"
   * Rhino Belieber *Craft a rhino bettle armor piece (craft any 1 rhino beetle armor piece)
  * Not so tough now, are you? *Kill a Wasp*
    * Wasperino Trollerino *Aquire a wasp weapon* (can be sword or dagger you can craft yourself) 
  * Mom! I don't wanna go to school! *Kill a Tarantula Brood Mother*
  * I gave you my soul. I gave you deeze eggs. *Kill an Ant Lion Overlord*

Umber What?

It glows? *Aquire a red gem*
* (+ Cockroach Safari ) Fancy Torch *Craft a glowing gem*
* (+ Umber What?) Mmmmmmmmmmmmmmmmm *Craft a smoothie matic machine*
 * Smooth a smoothie *just that* (Craft a smoothie)

Jems! *Aquire a jade berry or jade stone piece*
* Jems... Jems are trully trully amazing! *Craft any jade item*

It Belongs in a Museum! *Aquire an Altar Fragment*
* Much safer with me *Build an Altar"
* Use the whip *Craft a golem statue*
 

etc. you can add a few others:)

**Comment by purpleposeidon** [comment]
Double-jump: Kill more than one larva in a single jump. Requires monitoring the # of jumps statistic. Maybe it'd be fun if jumping on them gave you a bit of an upward bounce?

**Comment by vadis365** [comment]
closing because no new features should be added until the mod has been ported to a higher version.
