### ISSUE TITLE
heavy lag issue in Erebus both 0.3 and 0.4 in certain ares of the map

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#428]
So I was playing latest 0.3 the other day and I started getting serious lag in one area between fungal forest and swamp . Funny enough I always get this same lag issue in those 2 areas.

I  checked the F3 and seems it says is a Tick issue and checking that says is a Texturing issue.

I just upgraded to 0.4 and the issue is still present still a Tick issue but this time says it's a Level issue.

I noticed the lag happens when a Crushroom is present or when I'm near a swamp area or specific places in Erebus.

Likely cause I suspect is texturing code on Crushroom is buggy and is not working properly so the game needs to wait for missing textures making it lag a lot. Could you please investigate? If is not crushroom then it has to be some other mob found in those 2 areas.

**Comment by trollworkout** [comment]
I just wanted to mention I am on the latest erebus release 3 days ago and on the minimum forge release supported (which happens to be latest forge release ATM). And that this issue of heavy lag in certain areas has happened for a while now but only lately I have found those 2 biomes to be predictable in lag.

I am also using Optifine HD Ultra C1 1.7.10 and FastCraft and BetterFPS. I wasn't using these last 2 in 0.3 and I was still getting lag.

**Comment by ganymedes01** [comment]
Do you have a lot of glowworms or glowshrooms in that area?

**Comment by trollworkout** [comment]
@ganymedes01  possibly.  i will check again and let you know.

**Comment by ganymedes01** [comment]
They have been known to cause lag to people running slow computers, so it might be what's causing your issue.
There is a config option to disable them though, so you could also try turning those off and checking for lag again.

**Comment by trollworkout** [comment]
@ganymedes01 i am going to try that + disable glow on glowworms see if that helps

**Comment by ganymedes01** [comment]
backup your world first :)

**Comment by vadis365** [comment]
No further problems? Closing.
