### ISSUE TITLE
(suggestion) wandering villager-like mob in Fungal Forest that can be traded with

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#429]
A villager like mob that wanders around Fungal Forest and can be traded with for Erebus materials/weapons using jade pieces as their currency.

They don't live in houses, don't form villages and don't band together. They simply wander around in Fungal Forest and can be traded with. 

 They don't need any house mechanics or sky or wood doors or anything of that sort. They count any unique type of mushroom blocks as their max population and how many members are currently loaded in the nearby chunks. So having 14 unique blocks means 14 max individuals. Having only 7 individuals with 14 max population size makes them 50% more likely to multiply.  This can be affected by how many trades you unlock as well. 

They don't get attacked by anyone from Fungal Forest but will get attacked by Volcanic Desert mobs.

Could be a new mob or maybe that jumping mushroom you guys have could be intelligent mob instead.

**Comment by vadis365** [comment]
A system of trading with NPCs has already been discussed by the coding team.
It will involve ALL biomes with some sort of biome specific trading posts.
Each 'merchant' will trade for things not found in it's own biome.
Closing this issue for now as I'll open a new one when we are closer to implementing the system.
Thanks for the suggestion, when we are ready to add trading, I'll add your name to the new issue so you can add any ideas you may think of :)
