### ISSUE TITLE
(suggestion) please make fungal forest ground mycelium 

### ISSUE THREAD

**Issue by trollworkout** [ganymedes01/TheErebus#430]
just that. makes more sense to be able to grow any giant shrooms you want there

**Comment by ganymedes01** [comment]
It doesn't look good though )=
I think a better solution might be to make the mushrooms plantable on grass instead

**Comment by purpleposeidon** [comment]
Custom mycellium block!

**Comment by ganymedes01** [comment]
yeah that could work too XD

**Comment by vadis365** [comment]
iirc the giant shrooms will already grow on grass.
A custom mycelium block could be fun... not sure what it could do other than have a different texture though.

**Comment by vadis365** [comment]
Closing as no one has any new ideas about this. :P
