### ISSUE TITLE
Portal in erebus not activated

### ISSUE THREAD

**Issue by GrayCountertop** [ganymedes01/TheErebus#439]
after I created the portal and activated it I went through the the portal inside of the erebus wasnt activated. So I was trapped there.

I just went into creative game myself a wand thing put leaves in it and activated it myself but still if I wasnt playing with commands I would have been screwed.

**Comment by ganymedes01** [comment]
You should have crafted two staffs and taken one with you.
Though I'll admit that isn't written anywhere and that's our fault... I think I might make the recipe yield two staffs instead of just one, so that it kind of hints to the player they'll need more than one.

**Comment by GrayCountertop** [comment]
Yeah I kinda freaked out for a moment because I had trouble with Mariculture and Erebus colliding (Fixed it with a mariculture .cfg tweak) and I thought that I was having more problems with the mod.

Also theres no sort of ingame guide at all in the mod. Hopefully there arent more things like this.

**Comment by GrayCountertop** [comment]
Also you should probably tell them to take shears or more leaf blocks with them as well.

**Comment by ganymedes01** [comment]
Gave this some thought and decided not to actually change anything.
All of the materials to craft a second staff and shears are available in the erebus... you jumped through the portal, might as well go out exploring =P

**Comment by GrayCountertop** [comment]
Seems fair but honestly most will think its a bug. I would atleast give the player something that says like "Oops looks like the portal back is broken, I guess you'll have to fix it" Its an easy way to lose your items day one of erebus and thats no fun.

**Comment by ganymedes01** [comment]
Yeah I agree losing your items wouldn't be fun.
And I agree that there's not enough documentation on it, that's something we are hoping to solve for the future.
But I like the portal mechanic as it is, players will need to brace themselves before going in, anyone going unprepared will die, just like if you go to the nether unprepared you'll die (except the nether is easier because you can easily come back from it) :3
