### ISSUE TITLE
Spawn exit portal if difficulty is easy/normal?

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#440]

**Comment by vadis365** [comment]
Sounds like a plan.

**Comment by vadis365** [comment]
I will be adding some configuration options for the portal.
One of the options would be to not generate the structure at all but still the 'safe' air gap.
I guess that would also be vaguely connected.

**Comment by vadis365** [comment]
Config for no frame is added. 
Made leaves spawn in the portal frame but I still think the player should have to make the return staff....
