### ISSUE TITLE
Enter Erebus Dimension from any other dimension

### ISSUE THREAD

**Issue by Darkosto** [ganymedes01/TheErebus#441]
Would it be possible to allow teleporting to the Erebus from any dimension other than the overworld? I would like to allow the player to teleport from the end to the Erebus for modpack story purposes.  

This is the line relevant to this question:
https://github.com/ganymedes01/TheErebus/blob/master/src/main/java/erebus/block/ErebusPortal.java#L87

Thank you!
Darkosto

**Comment by vadis365** [comment]
Sure, this should be a very easy tweak. I'll look in to it for you.
