### ISSUE TITLE
"Flashing" Background

### ISSUE THREAD

**Issue by Darkosto** [ganymedes01/TheErebus#446]
Hello! There are a frequent number of times the background of the dimensions starts flashing during gameplay. This issue seems to pop up randomly, and restarting the client does not always help. I've turned on/off most of my video settings to eliminate it but have not stopped it. Also, I've tried with/without a texture pack and it continues to flash. 

I've included a short video to give you an idea of what is happening (Please note: the flashing on the video is much slower than what I see in the actual game window). 

https://youtu.be/QSJ-hM1vQvI

I don't want anyone to get a seizure! :p

Thank you for all of your help!!
Darkosto

**Comment by vadis365** [comment]
Not sure this one is due to Erebus. I noticed it started after the glowing cube thing you were adding to the quests crashed you out on your stream. Could you see if it happens in the Overworld and End in that world. It may be that it's renderer is causing this.

**Comment by Darkosto** [comment]
I've gone through each dimension and this does not happen anywhere else. It did start happening before that crash you mentioned happened, since the first time I experienced that crash was on Friday, and I noticed this on Wednesday and Thursday.

**Comment by vadis365** [comment]
Hello,
Would it be possible to do a binary test on your mods? This issue has never happened before and I cant seem to duplicate it. I run a personal server with a modest 68 mods and don't have this issue.
I think it must be another mod causing it to happen. Thanks for your patience ;)
Cheers,
Me.

**Comment by vadis365** [comment]
Hello,
I looked at the code we use for fog and we honestly don't do anything funky. All we do is set the fog colour based on biome which shouldn't effect the global render in the way you are reporting.
I really think this either a mod incompatibility or worst case something GPU based... maybe drivers?
Something, somewhere, may or may not be causing a glitch on the light-map rendering but I'm not sure where as this is the only report we have had of this issue. Let me know if you figure out what combination of mods replicates this please.
Cheers,
Me.

**Comment by Darkosto** [comment]
No worries! I'll keep poking around the pack and see what I can come up with :)

**Comment by vadis365** [comment]
Doesn't seem to be our fault this time - closing.
