### ISSUE TITLE
Biomes ID higher than 127

### ISSUE THREAD

**Issue by KorDum** [ganymedes01/TheErebus#447]
java.lang.IllegalArgumentException: Erebus biome IDs cannot be higher than 127 or smaller than 0!
Why? Mod doesn't work with BoP.

**Comment by Bogdan-G** [comment]
This issue has been raised many times, in the code is to plug the ID was not above 127, they think that the biomes higher than ID 127 will be generated in the overworld, but this is not true in the bud.

**Comment by vadis365** [comment]
Bogdan is wrong. If you assign the biome ID's wrong you will have issues with biomes appearing in the Overworld. The only way you can use The Erebus with BOP is to assign ALL Erebus biome ID's to 127 or below in any free biome ID's. You will also have to have the biome ID you use +128 free as The Erebus uses vanilla's biome mutations. Your game will crash if you do not do this.

**Comment by Bogdan-G** [comment]
@vadis365  what problems? I have no problems, no generations biomes in overworld at BoP or default types of generation. Biomes Erebus, as well as tropicraft or twilight forests do not overlap in the ordinary world.

If you mean conflicts with hooks bop, it needed plug and not to impose restrictions.

**Comment by KuroNeko87** [comment]
I know this Is closed, but the issue that the devs are raising was fixed in forge AGES ago.
