### ISSUE TITLE
Portal not activating

### ISSUE THREAD

**Issue by LyingCak3** [ganymedes01/TheErebus#453]
Hey,

I cannot get the portal to the Erebus to activate.  I have followed the directions on the forums to the letter and still nothing.  Unfortunately I do not see any errors in the logs about why it is not working.  I have included a picture of my portal set up.

![2015-12-21_17 12 11](https://cloud.githubusercontent.com/assets/5199260/11944838/517069e4-a806-11e5-99f2-2aa1a27d94f3.png)

**Comment by ganymedes01** [comment]
This is how you build a portal: http://minecraft.curseforge.com/projects/the-erebus

Not sure why the old way is still on the forums, but I blame @vadis365 for it.

**Comment by purpleposeidon** [comment]
I see the curseforge page doesn't mention that you need a second one; is it intentional to be excitingly trapped? :D

**Comment by vadis365** [comment]
@ganymedes01, @LyingCak3 The new portal instructions are linked to 3 times in the forums post - I left the old ones up for people that are using older versions. Blame accepted but I have no regrets :P

@purpleposeidon - yes we worked out all the things that are needed to make a new staff are available in the Erebus - consider it a life lesson :P
