### ISSUE TITLE
Enemies Hit Players Through Walls

### ISSUE THREAD

**Issue by Darkosto** [ganymedes01/TheErebus#454]
I've encountered an issue where Wasps will hit the player through a wall. I made a home in an amber structure with all entrances blocked off and the wasp managed to still hit and kill me through the blocks. This seems to happen with other mobs regularly, but I can confirm from play testing with Wasps.

Erebus mobs seem to do this more than other vanilla mobs I've encountered. I'm aware of the corner block glitch where some mobs can hit you if you stand in a corner opposite from them, but Erebus mobs seem to have a much farther reach and in some instances hit through places that are not a corner.

**Comment by vadis365** [comment]
Yeah, this has been an issue for people for a while.
I'll work on it and maybe will have it sorted and compiled for tonight.

**Comment by vadis365** [comment]
This is now fixed for Wasps.
The diagonal hits through blocks can still happen though - that is mojang's fault as have tested it on Zombies and slimes and they do it too.
