### ISSUE TITLE
Fungal Soldier Ants need a drop

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#458]
Not sure what to add here. I'll open it up to the forums and see what people can come up with...

**Comment by Darkosto** [comment]
It might be interesting to have them drop rotten flesh, this would allow that item to be available without having to leave the Erebus.

**Comment by vadis365** [comment]
Zombie flesh is a good idea, but I may make it drop something else that can be crafted in to zombie flesh. Don't want to make it too easy ;)

**Comment by vadis365** [comment]
Other suggestions so far are a diamond block (just no.) or some sort of special mushroom that could be crafted for a better stew (titan stew covers this so maybe not) or a smoothie ingredient. The smoothie ingredient seems like the best idea so far.
So:
Base zombie ant drops something to craft in to rotten flesh. This thing could also be used to craft something else (undefined as yet)
Soldier zombie ant as above but also drops some sort of special 'shroom used in a new smoothie.
Both would still rare drop pheromones for the ant medallion.

**Comment by vadis365** [comment]
I think something along the lines of 'zombie ant plates' would be the thing to craft in to rotten flesh.
There is a new item planned that will be implemented with the new dungeon - it would tie up nicely as the material that could be used to repair this mystery item too.
