### ISSUE TITLE
Anti-venom change

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#459]
Anti-venom should be an effect that lasts for a duration. 1 minute would be good.
I was thinking of making it like a hunger bar with a gui overlay that counts down in half bottles.
The effect shouldn't be cumulative though so, drinking another one would only top up to the max of 1 minute. This would make anti-venom different from beetle juice and provide a bit more protection for the player against the poison effect based mobs in the dimension ;)

**Comment by purpleposeidon** [comment]
An anti-venom potion effect might be more sensible.

**Comment by vadis365** [comment]
Tool late. I have made it now :P

**Comment by vadis365** [comment]
Not finished with this after all. I have a new texture for the overlay bar and I think I will make bottles cumulative up to the max amount (equal to 1 bucket).

**Comment by vadis365** [comment]
tweaked and done, I hope...
