### ISSUE TITLE
Preserved block basic mob rendering

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#460]
Mobs from Head Crumbs, Grimoire of Gaia and Twilight forest all start to render half way up the preserved blocks - not a problem if the player goes through and edits every mob in the config,  as this has been provided for. It would make more sense to me if the start of all mobs was Y0 on the preserved blocks for non mod/vanilla mobs as this would involve less editing because most derps would be due to scaling.

**Comment by ganymedes01** [comment]
I'll fix it :3
Sorry for going missing. Jade and I are moving to our new place so things are a bit chaotic at the moment =P

**Comment by vadis365** [comment]
No worries man. The mess will still be here when you are up for it. :)
Good luck with the move and things.

**Comment by vadis365** [comment]
I forgot to add the stag beetle, stag beetle mob, bed bugs, soldier zombie ants and zombie ants new rendering scales to the hard coded entity dimensions - whoopsie!

**Comment by vadis365** [comment]
closing because this issue can actually be fixed easily, probably, but it hasn't - so if anyone cares about it they can manually change the configs to compensate.
