### ISSUE TITLE
Release Due For 12th/13th of January

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#461]
I am going to put a release out with all the latest additions this coming week.
There is a fair bit of extra stuff added but some things are a little unfinished.
For the release I will hide all the new dungeon things from NEI and the creative menus as they are not ready yet.

Things to finish for release (Putting this here so I remember).

Stag Beetle:
- [x] Drops, Crafting, Saddle textures, Spawning
- [x] Advanced AI and Animations

Stag Beetle Larva:
- [x] Easy one to do just a quick model and texture tweak

Soldier Zombie Ants:
- [x] To spawn in fungal forest for now also, add new mushroom drop (useless atm).

New Smoothie:
- [x] will contain zombie mushroom (function unknown... help?)

Bed Bug:
- [x] Shrink size and spawn 3 on placing a bed, change drop to wool, edit stats to be weaker.

Sarcastic Czech Giant Mushroom:
- [x] Add air check for bone-mealing.

Can't think of anything else, but will wing it and fix anything I spot along the way.

**Comment by ganymedes01** [comment]
formatted it so you can't say I didn't help <3

**Comment by vadis365** [comment]
oh so helpful - thanks :P
