### ISSUE TITLE
[Massive Lags] After installing new build with new Forge version

### ISSUE THREAD

**Issue by SugarDaddii** [ganymedes01/TheErebus#469]
New Erebus Version needs Forge 1566 for 1.7.10!
So i installed all the new stuff and after logging in SSP i haave massive Laggs and FPS drops!

normally 70-100 fps ----> after 12-30 fps!

Can you help me!

**Comment by vadis365** [comment]
I have no idea we have changed nothing in the mod that should cause any lag.
In fact in the last few months a major re-write of potential code that could cause lag was achieved.
It may be another mod causing it. Try adding Fastcraft.

**Comment by SugarDaddii** [comment]
is it possible to change forge version back to 1558? because i think forge is the problem now?!
