### ISSUE TITLE
Incompatability with Iguana Tinkers Tweaks

### ISSUE THREAD

**Issue by tetsune** [ganymedes01/TheErebus#470]
Pickaxe/Tools with Stonebound parts cannot be replaced, disables the config file so you can use even stone parts for tools, and it disables the ability to repair your tool via inventory crafting menu.

**Comment by vadis365** [comment]
We have no idea why this happens - nothing in The Erebus code should effect how other mods' recipes work. It's not really a case of not caring about this issue, it's more about I have no idea what causes this and no idea how to fix it - I'm afraid this is just going to stay as it is unless iguana tweaks fixes it at their end...
