### ISSUE TITLE
No attack cooldowns on Erebus mobs

### ISSUE THREAD

**Issue by Funwayguy** [ganymedes01/TheErebus#473]
It seems that many mobs from the Erebus have no attack cool downs meaning the speed at which the player takes damage is completely reliant on the player's invincibility frames. This is extremely noticeable on mobs such as scorpions that pick you up, locking you in their collision bounds and causing a very quick death as you've probably seen by now. A delay of about 1 second between attacks on most mobs would be sufficient.

**Comment by vadis365** [comment]
The scorpion was always intended to be a quick death from suffocation. I can change this but I think it will make the mob too easy fight. I'll do some stuffs.

**Comment by vadis365** [comment]
meh - fixed scorpion to have a cool down - I may increase the attack damage once testing is resumed.
