### ISSUE TITLE
Bug repellent block unremovable

### ISSUE THREAD

**Issue by Funwayguy** [ganymedes01/TheErebus#474]
Placed bug repellent blocks are not set to be replaceable (like liquids) nor have a collision box meaning once placed, it is impossible for a survival player to remove the block if they decide they don't want it to be there any more.

**Comment by vadis365** [comment]
Strange. This block should be breakable by the player. Will look in to it.

**Comment by vadis365** [comment]
This is fine. It does actually have a small collision box and the player can break the block in one hit with a fist. Closing due to Funway wasting my time. :P
