### ISSUE TITLE
Erebus mobs can attack even when dead

### ISSUE THREAD

**Issue by Funwayguy** [ganymedes01/TheErebus#475]
It appears that a custom attack AI used in Erebus mobs is missing a check for whether or not the attacker is still alive allowing mobs to still do damage while their death animation plays.

The 'attacker.isEntityAlive()' check should be placed within these two methods:

https://github.com/ganymedes01/TheErebus/blob/master/src/main/java/erebus/entity/ai/EntityErebusAIAttackOnCollide.java#L42

https://github.com/ganymedes01/TheErebus/blob/master/src/main/java/erebus/entity/ai/EntityErebusAIAttackOnCollide.java#L59

**Comment by vadis365** [comment]
Good catch - will do. :)

**Comment by vadis365** [comment]
Added Boolean. Lets hope that's all it is ;)
