### ISSUE TITLE
GANY!

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#478]
Could you add @Funwayguy to the Erebus repo for editing rights - He's a good coder and has been helping with a few bits. It would be nice if he had editor rights.

**Comment by ganymedes01** [comment]
Done. I'll be back next week for a chat probably. Been busy sorting out passports and a bunch of legal stuff. Don't let him break everything, I haven't had time to check the commits lately ;D

**Comment by vadis365** [comment]
LOL! Don't worry - I'm the one breaking stuff at the moment.
Will be good to catch up with ya mate ;)

**Comment by Funwayguy** [comment]
Don't worry I won't be doing much anyway. I have a few of my own mods to work on at the moment but I will double check with vadis before committing anything major.

**Comment by vadis365** [comment]
Just wanted to give you the option Funway ;)
I trust you. Sort of :P
