### ISSUE TITLE
crash report when updating kcauldron

### ISSUE THREAD

**Issue by runescapejon** [ganymedes01/TheErebus#483]
When i updated my kcauldron to this 
https://repo.prok.pw/pw/prok/KCauldron/1.7.10-1614.196/
and i got this crash report 
http://pastebin.com/cvC5XrjA

**Comment by runescapejon** [comment]
nevermind it was a kcauldron issue you can close this

**Comment by vadis365** [comment]
O.K. Will close, although...
erebus{0.3a} [Erebus] (TheErebus-0.3a.jar) 
That is an old version of The Erebus. At the time of writing we are at 0.4.5 - please update as several things have been changed and fixed.
