### ISSUE TITLE
Tinkers' Construct Item Duplication bug with Block O'Bones

### ISSUE THREAD

**Issue by Kolrolf** [ganymedes01/TheErebus#485]
I've got the 0.4.5 version of Erebus installed.  I died due to burning and one of the items I had on me was a Tinkers' Construct mattock.  When I got back to my BoB I noted my mattock nearby and picked it up.  I cracked open the BoB and got a second identical mattock out of it.
That was the only TC tool I was carrying with me at the time.

**Comment by vadis365** [comment]
Can you duplicate this bug with other items? I will look in to this.

**Comment by vadis365** [comment]
No response from issue poster - closing for now - may reopen later if issue is able to be duplicated.

**Comment by Kolrolf** [comment]
Sorry, just noticing this.
Yes, this bug happens with any TC tool or weapon that I'm carrying when killed.  It doesn't happen for any vanila minecraft items or other modded items that I'm carrying, only TC stuff.
Erebus version 0.4.5
Tinker's Construct version 1.8.8
Forge version 10.13.4.1614
