### ISSUE TITLE
Wasp Can Attack Through Blocks Below Players

### ISSUE THREAD

**Issue by Darkosto** [ganymedes01/TheErebus#492]
Hello!

While doing some testing today, I discovered while standing on a 1 thick floor, wasps can attack from below that block and still hit/poison the player. I wasn't able to tell if they can hit the player from the top or sides, but they can most definitely hit the player through 1 full block beneath. 

Thanks :)
Dark

**Comment by vadis365** [comment]
Will be fixed in the next release - sorry about the delay :P

**Comment by vadis365** [comment]
I think the best way of handling this for now, until mojang actually make decent collision detection, would be for the wasp to only target players it can see using the EntitySenses methods.
There is a problem using that method that I know of; when players hide behind double high plants the mob AI takes it as hiding behind a solid block... I'll change it for now and see how we go.

**Comment by vadis365** [comment]
Should be fixed now?
