### ISSUE TITLE
Optifine's Fast Rendering Causes Transparency Issues

### ISSUE THREAD

**Issue by wtchappell** [ganymedes01/TheErebus#496]
Please feel free to immediately resolve this as Optifine's problem - I'm more or less just opening this so the next person searching for this error finds something useful.

If you have Optifine's 'Fast Render' option turned on, all transparent blocks in the Erebus dimension develop white fuzz when looked at in certain directions from more than a certain distance. This is most noticeable on leaves, vines, and small plants. It doesn't look like it happens in other dimensions, like Twilight Forest.

Disabling 'Fast Render' appears to fix the issue - turning on 'Multi-Core' chunk loading may also exacerbate issues, and so using 'Default' chunk loading is also probably a good idea.

**Comment by vadis365** [comment]
Yeah, looks like an optifine thing - probably disabling the tranparencies.
