### ISSUE TITLE
Betweenlands integration?

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#498]
(I haven't tried the mod yet. Just an idle thought. Maybe it'd be part of progression thing...)

**Comment by vadis365** [comment]
There was a suggestion long ago that we allow BL druid circles or maybe a random portal tee spawn in the Erebus somewhere as a sort of special Easter egg cross mod fun thing.

**Comment by vadis365** [comment]
Nothing planned for this so closing.
