### ISSUE TITLE
[New Feature] Config Option to Disable Portal Creation

### ISSUE THREAD

**Issue by Kraise** [ganymedes01/TheErebus#501]
Would it be possible to add a config option that completely disables the creation of the Erebus portal, similar to how Twilight forest has a number of options to disable theirs? I know this defeats the purpose of the mod, but it would be a nice option as a temporary fix for issues like #500 where people are crashing servers every time they try to make and enter the portal, and disabling the dimension is the only option until a fix is released.

**Comment by vadis365** [comment]
I'm not keen on adding this as a 'feature' because it disables the whole idea of the mod.
I think it would be more up to server admins to implement rather than me. I would rather like to fix any bugs that cause crashes than disabling the dimension.
