### ISSUE TITLE
Add string with keybindings for powered glider tooltip

### ISSUE THREAD

**Issue by Ghostlyr** [ganymedes01/TheErebus#508]
TODO: Is necessary to add localizable tips with assigned glide and poweredGlide keys. Such as in RFDrills mod: https://github.com/goldenapple3/RFDrills/blob/master/src/main/java/goldenapple/rfdrills/util/StringHelper.java

Unfortunately, I can't do this =)

**Comment by vadis365** [comment]
Hello,
I'm not sure what you mean here. The link just gives me a 404.
Do you mean a tool tip in the configuration menu for the keybinds?
If so I'm not sure that is entirely necessary as the kebind names explain what each key does anyway.
Cheers,
Me.

**Comment by Ghostlyr** [comment]
Oops, sorry. URL edited.
I'm talking about glider armor  tooltip:

```
	public void addInformation(ItemStack stack, EntityPlayer player, List list, boolean flag) {
		if (canFly()) {
			list.add(StatCollector.translateToLocal("tooltip.erebus.poweredGlider"));
			// TODO Add tooltips with keys assigned to glide and poweredGlide as variables
		}
	}
```
Not everyone understands what buttons to push to fly, and always open the control settings is very uncomfortable.
It is necessary to realize the utility receiving binded buttons as is done in RFDrills:

```
    public static String writeModeSwitchInfo(String unlocalizedName, KeyBinding keyBinding) { //vanilla bindings
        return writeModeSwitchInfo(unlocalizedName, keyBinding.getKeyCode());
    }
```

**Comment by vadis365** [comment]
Ah I see. Sure that should be easy to do ;)
