### ISSUE TITLE
Magma River (structure)

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#51]
A river of Lava. That's it, pretty much. Spawns throughout the Volcanic Desert and Charred Forest.

**Comment by SMEZ1234** [comment]
Made an initial design. Tell me what you don't like about it and I'll fix it up.

**Comment by vadis365** [comment]
Awesome - I'll have a look after work.
Thanks Sean.

**Comment by SMEZ1234** [comment]
Closing this issue until someone tells me otherwise.

I know I haven't done any work on the Erebus recently, I've had zero free time. Sorry for that. Hopefully I'll find some time to get back to it soon.
