### ISSUE TITLE
Bug with Galacticraft

### ISSUE THREAD

**Issue by THEVOLCO** [ganymedes01/TheErebus#512]
Hi,
There is a bug with Galacticraft that makes the game crash when you try to enter the Erebus.
Here's the crash report:

http://pastebin.com/vpB7ESWx

**Comment by THEVOLCO** [comment]
Hi,
There is a bug with Galacticraft that makes the game crash when you try to enter the Erebus.
http://pastebin.com/vpB7ESWx

**Comment by vadis365** [comment]
Hello,
Looks similar to this. Try changing Erebus' biome IDs.
https://github.com/micdoodle8/Galacticraft/issues/1342#event-212070532
Cheers,
Me.

**Comment by THEVOLCO** [comment]
Ok thx :)
