### ISSUE TITLE
Are you still alive?

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#518]
Would be good to say hello, even if you don't want to help fix this nest of spaghetti. :P

**Comment by ganymedes01** [comment]
Define alive

**Comment by ganymedes01** [comment]
I'll show up this weekend XD

**Comment by vadis365** [comment]
Sentient with the ability to formulate abstract thoughts.
Or to laugh at toilet humour ;)

**Comment by ganymedes01** [comment]
Quick tell a poop joke

**Comment by vadis365** [comment]
Poop is a crap palindrome.

**Comment by vadis365** [comment]
What happened when the creeper pooped out TNT?
He was destroyed!

**Comment by ganymedes01** [comment]
I guess I'm dead then because those weren't funny at all lol

**Comment by vadis365** [comment]
You passed. :P
Turing test verified.

**Comment by buttilda** [comment]
I am.
But it's software release time at work, so I've been very busy and stressed lol. If this week goes okay I'll jump in for a chat :3 (or to re-write everything you've done so far, as I tend to do)

**Comment by vadis365** [comment]
Scooby-dooby-doo where are you?
Not spoken - sending out a search party for you ;)

**Comment by buttilda** [comment]
Sorry... email me.

(don't mean to be cryptic but don't want to say much in here)
