### ISSUE TITLE
Bug with thermal foundation

### ISSUE THREAD

**Issue by THEVOLCO** [ganymedes01/TheErebus#520]
Hi,
there are blizzes from thermal foundation spawning in the erebus. Is this a bug?

**Comment by vadis365** [comment]
Hello,
Yep this is a bug, but not with The Erebus.
The only way I found to fix this was to 'be a jerk' and disable them from Thermal foundation's config.
I'm hoping team CoFH will add a config to blacklist them from dimensions as it doesn't only happen with this mod.
Cheers,
Me.

**Comment by THEVOLCO** [comment]
ok thx :)
