### ISSUE TITLE
Question: Bot Fly Larvae

### ISSUE THREAD

**Issue by Darkosto** [ganymedes01/TheErebus#522]
Heya!

Just a quick question, since I don't have a way to contact Vadis easily :p

Do the botfly larvae persist after death? And how many can you get? Also, will 1 bucket remove multiple larvae?

Thanks! :D

**Comment by vadis365** [comment]
Hey ;)

I think they persist - wrote them 2 years ago so my memory is not reliable on that.
You can get up to 3 'in' you.
1 bucket removes 1 larva.

*edit - just checked code above is correct :P

**Comment by Darkosto** [comment]
Okay! Sounds good :) Thanks for the information!!

**Comment by vadis365** [comment]
persistence
https://github.com/ganymedes01/TheErebus/blob/mc1.7/src/main/java/erebus/entity/EntityBotFlyLarva.java#L78

1, 2, or 3 being removed after drinking bambuckets of beetle juice
https://github.com/ganymedes01/TheErebus/blob/mc1.7/src/main/java/erebus/entity/EntityBotFlyLarva.java#L115
