### ISSUE TITLE
Portal Structure

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#529]
Not looking forwards to porting this - it may take a while.
Need to add the keystone and portal activator item back.
Need to add the offering altar back for the gem.
The teleporter code will have to be changed as it is a port from before @purpleposeidon 's portal was implemented - but it should be easy enough to 'fix'.

**Comment by vadis365** [comment]
added old one back -it works.

**Comment by purpleposeidon** [comment]
:<

**Comment by vadis365** [comment]
@purpleposeidon - don't worry, your beautiful work will be added back once I figure out other things.
It's been a long time in the works and there is much more to go :P

**Comment by vadis365** [comment]
added the one @purpleposeidon made when I released :)
