### ISSUE TITLE
Re-introduce crafing recipes

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#535]
Stuff that is in game already and have the relevant items for crafting can be added back in game.
Tools and armour should be good to go.
The manufactured blocks like stairs etc. should also be good to go.
The Sprint leggings have a custom crafter.
The portal gem needs an altar and custom crafter.
The Smoothie maker also has a custom crafter and a hell of a lot of other things that need doing.

**Comment by MokahTGS** [comment]
Ores in 1.12.2 version don't seem to have a use or be smeltable into anything.  They also need to be added into the Ore Dictionary.

**Comment by vadis365** [comment]
Some of the ores are just there for mod compatibility - like tin, copper, etc
They are already ore dicted and should work as intended, there is an option to enable/disable in the config.
See here for smelting and scroll down for ore dict names:
https://github.com/ganymedes01/TheErebus/blob/mc1.12/src/main/java/erebus/recipes/RecipeHandler.java#L89
