### ISSUE TITLE
Can't Recreate Portal to the Erebus MC 1.7.10 v .4.7 

### ISSUE THREAD

**Issue by MikoSphinx** [ganymedes01/TheErebus#538]
After breaking the first portal on our server, it is now impossible for anyone to create another one, because the wand doesn't activate the structure.

**Comment by vadis365** [comment]
Hello,
Sorry to hear you are having problems. The portal should be able to be re-lit no problem.
If there are any leaf blocks too near to the portal structure it will be invalid - that may be your issue.
Also just in case... you did fill the portal frame with leaves again before trying to activate?
Let me know if any of this helped.
Cheers,
Me.

**Comment by MikoSphinx** [comment]
Tried Oak Leaves and nothing has changed, to make the portal work. The nearest leaves are at least 5 blocks away and they are mod leaves, not vanilla.

**Comment by MikoSphinx** [comment]
The nearest leaves are at least 5 blocks away and they are mod leaves, not vanilla.

**Comment by purpleposeidon** [comment]
Gotta screenshot?

**Comment by WWDragon** [comment]
I'm the tech person on Miko's server.
I think I figured out what happened.

When originally installed to our modpack, it was using version .3a and so the first portal was built with the original portal method shown on these two pages:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287600-0-2pre10-the-erebus-dimension-of-the-arthropods-0
and
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2244153-erebus-update-0-4-7-bug-fix-released

Only yesterday after she reported this did I find the new portal method, clued in by  vadis365's response comment above, which is here:
http://minecraft.curseforge.com/projects/the-erebus

All the minecraft videos also show the old portal method, so we thought it was just broken.
After trying the new method, it works and can be remade over and over.
So, no bug.... just missinformation from old method and both the pages on minecraftforum.net not having updated tutorial.

**Comment by vadis365** [comment]
Great stuff, glad you have it sorted :)
There are at least 4 links on the forums OP page saying where to look for the new portal instructions - lol
I'll remove the old instructions - they were just there for people that hadn't updated.
