### ISSUE TITLE
Fake torches 

### ISSUE THREAD

**Issue by XPiriTorig** [ganymedes01/TheErebus#542]
If you put the  bamboo torches on the wall, there are fake and they do not spend. Also appearing fake light sources.
![2016-06-29_16 18 30](https://cloud.githubusercontent.com/assets/19643070/16453344/27f6e6f6-3e15-11e6-9896-0016dc6b1ff0.png)

**Comment by vadis365** [comment]
Ummmm... bamboo torches are not supposed to be able to be placed on the sides of blocks.
How did you place them on the wall without a block under it? Also that is only the top part of the double block I don't know how you can only place half the torch.
1.7.10 Erebus will no longer be supported as we are in the process of updating the mod and cannot spare the time unless it is a critical bug. Thanks for the report tho' ;)
