### ISSUE TITLE
Help required.

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/TheErebus#546]
If anyone else wants to help with this project please do.
I'm getting a bit pissed off with being the only coder.

**Comment by BunnyCinnamon** [comment]
I think your mod is really good, and very used among the players. Please keep up the good work ^-^. I'd help, but I'm busy with college and all I get is 1 week of vacations, fml. :<

**Comment by TheCricket** [comment]
I have some extra time this week I will get as much done as I can
