### ISSUE TITLE
BUG 1.7.10 kCauldron server crash

### ISSUE THREAD

**Issue by digimbyte** [ganymedes01/TheErebus#547]
Lov Erebus, but the server randomly dies with the following

it looks like this might happen when the dimension is unloaded from memory and something cant be saved ( I guess)

> [16:52:03] [Server thread/INFO] [Minecraft/]: [Multiverse-Core] World 'DIM66' was unloaded from memory.
> [16:52:03] [Server thread/INFO] [FML/]: Unloading dimension 66
> [16:52:03] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ServerTickEvent@7c310927:
> java.lang.NullPointerException
>   at erebus.world.SpawnerErebus.onServerTick(SpawnerErebus.java:47) ~[SpawnerErebus.class:?]
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler_282_SpawnerErebus_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-R0.1-SNAPSHOT]
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-R0.1-SNAPSHOT]
>   at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:265) [FMLCommonHandler.class:1.7.10-R0.1-SNAPSHOT]
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:797) [MinecraftServer.class:?]
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> [16:52:03] [Server thread/ERROR] [FML/]: Index: 6 Listeners:
> [16:52:03] [Server thread/ERROR] [FML/]: 0: NORMAL
> [16:52:03] [Server thread/ERROR] [FML/]: 1: ASM: chylex.hee.mechanics.charms.handler.CharmPouchHandler@305cc975 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [16:52:03] [Server thread/ERROR] [FML/]: 2: ASM: chylex.hee.mechanics.misc.TempleEvents@2132a125 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [16:52:03] [Server thread/ERROR] [FML/]: 3: ASM: mca.core.forge.EventHooksFML@6d799ed2 serverTickEventHandler(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [16:52:03] [Server thread/ERROR] [FML/]: 4: ASM: codechicken.chunkloader.ChunkLoaderEventHandler@33846831 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [16:52:03] [Server thread/ERROR] [FML/]: 5: ASM: erebus.world.teleporter.TeleporterHandler@57b328a8 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [16:52:03] [Server thread/ERROR] [FML/]: 6: ASM: erebus.world.SpawnerErebus@599876a3 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [16:52:03] [Server thread/ERROR] [FML/]: 7: ASM: org.dynmap.forge.DynmapPlugin$ForgeServer@8dfb4f1 tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [16:52:03] [Server thread/ERROR] [FML/]: 8: ASM: ivorius.reccomplex.events.RCFMLEventHandler@5f18defb onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [16:52:03] [Server thread/ERROR] [FML/]: 9: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@408068fe tickStart(Lcpw/mods/fml/common/gameevent/TickEvent;)V

**Comment by BunnyCinnamon** [comment]
Dont unload the world. Also, your crash report looks like this? http://pastebin.com/aubrhYvn

**Comment by vadis365** [comment]
Closing - been nearly a year and 1.7.10 is no longer supported
