### ISSUE TITLE
Duplicate Biomes

### ISSUE THREAD

**Issue by SylisMC** [ganymedes01/TheErebus#548]
Hey,
i was looking at the used Biomes and it appears that the erebus is using 2 sets of biomes.
(ive seen this with 3 other mods as well)

these are in the config files by default

```
    Underground Jungle"=100
    Volcanic Desert"=101
    Subterranean Savannah"=102
    Elysian Fields"=103
    Ulterior Outback"=104
    Fungal Forest"=105
    Submerged Swamp"=106
    Fields - Forest"=107
```

But there is also a second Set of IDS being reserved for the Erebus

```
> 228 is Occupied by Undergound Jungle M (erebus.world.biomes.BiomeUndergroundJungle)
> 229 is Occupied by Volcanic Desert M (erebus.world.biomes.BiomeVolcanicDesert)
> 230 is Occupied by Subterranean Savannah M (erebus.world.biomes.BiomeSubterraneanSavannah)
> 231 is Occupied by Elysian Fields M (erebus.world.biomes.BiomeElysianFields)
> 232 is Occupied by Ulterior Outback M (erebus.world.biomes.BiomeUlteriorOutback)
> 233 is Occupied by Fungal Forest M (erebus.world.biomes.BiomeFungalForest)
> 234 is Occupied by Submerged Swamp M (erebus.world.biomes.BiomeSubmergedSwamp)
> 235 is Occupied by Elysian Forest M (erebus.world.biomes.BiomeElysianFields$BiomeElysianForest)
```

it causes the erebus to use up an extra 8 biomes and its unnecessary and ive been told it causes extra lag because minecraft tries to load both but i cant confirm that is true.  it also makes it more difficult to configure to work with other mods because you can only have 255 different biomes. and 60 of those are used for vanilla minecraft.

please fix as soon as conveniently possible (: thanks

**Comment by SylisMC** [comment]
Update: ive noticed that if i change the biome in the config file. the duplicate biome id is 128 numbers above the config file id, (so if i set the Fungal Forest to 40, the seconds Fungal Forest would be 168)
not sure if that helps

**Comment by TheCyberBrick** [comment]
This is not a bug. The fact that you saw this with 3 other mods should hint that it isn't a bug.
https://github.com/Angry-Pixel/The-Betweenlands/issues/325

**Comment by vadis365** [comment]
This isn't a bug. It is just the way Minecraft works. We cannot do anything to change the hardcoded rules for Biome mutations. Sorry.
