### ISSUE TITLE
Needs a mechanism for finding structures

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/TheErebus#553]
The pyramid & maze are too difficult to find.

**Comment by vadis365** [comment]
Look harder - they are massive.
Hint: The Umbergolems inside it have boss bars to make it easier to locate.
But, yeah, I was thinking about making it a proper structure with an AABB for ease of everything but nothing much is happening for the immediate future. I have a fair bit done for 1.10.2 including the dimension and most gen sorted and a load of other bits - but doing other stuff atm.

**Comment by vadis365** [comment]
Working on adding a map based on the same idea as the Twilight Forest Magic map.
Spoken to the TF team and looked at their implementation, atm I have a working Erebus map item that displays the biomes. Next will be to change some structure gen and add ways of storing the locations to the map data. Erebus only has 2 dungeons worth noting atm although it also has several mini-dungeons, I may have to add some place markers for future dungeon gen or mark the mini-dungeons on the map for the time being so it doesn't look so bare. I'm working on changing the maze and pyramid gen code atm to make it always be in a volcanic desert and more sensible positioned. All very WIP :P

**Comment by vadis365** [comment]
Closing as this is being addressed in dev.
The Big structures are generated in a different way and generate using different rules now.
