### ISSUE TITLE
TheErebus has a crash

### ISSUE THREAD

**Issue by Shindubato** [ganymedes01/TheErebus#554]
Erebus can not use biome ID 100 because it's being used by biomesoplenty.common.biome.overworld.ocean.BiomeGenKelpForest@75f1424a
Pls I love your mod Fixed it :c

**Comment by vadis365** [comment]
Exactly what the crash report says.
You have a biome ID conflict.
Erebus biomes must be below 127 so make sure any Erebus biome has it's base id AND it's base id + 128 free as we use mutations that use biome ID +128.
Try moving the erebus biome that is id 100 to another free number under 127 in the configuration file.
This will solve your issue.
