### ISSUE TITLE
Return portal

### ISSUE THREAD

**Issue by TheLemein** [ganymedes01/TheErebus#557]
Made the portal, can get in, but no leaving out, the keystone will not activate with the staff. tried multiple portal builds with and without leaves, structure types. using 1.7.10 with erebus 0.4.7

**Comment by purpleposeidon** [comment]
Got a screenshot? There might be trouble if you build your portal right next to a tree; I forget the details.

**Comment by TheLemein** [comment]
I have to laugh, the hour I bashed my head on this.. I ended up dimensiontp to leave the place. Went back to take pictures......It finally worked... changed nothing.. just hit it with staff again... very weird... but here are the pictures regardless.. 

![1](https://cloud.githubusercontent.com/assets/24373727/20868714/9a0b4a00-ba27-11e6-8c25-da24bb528d2f.png)
