### ISSUE TITLE
Night vision [1.7.10]

### ISSUE THREAD

**Issue by Psithief** [ganymedes01/TheErebus#558]
If `The Erebus` is installed, effects of night vision with magnitude 1 are instantly removed because this mod is assuming it is the only source of night vision.

This is causing mod incompatibilities, specifically two mods fighting to give the player nightvision or take it away makes for a very unpleasant constant flashing.

Maybe you could pick a different magnitude or make it configurable? The problem being that `1` is pretty commonly used - everyone is trying to avoid conflicting with potions but nobody tries to avoid conflicting with other mods.

https://github.com/ganymedes01/TheErebus/blob/mc1.7/src/main/java/erebus/core/handler/GogglesClientTickHandler.java#L34

**Comment by vadis365** [comment]
This will be fixed in newer versions 1.7.10 is no longer supported
