### ISSUE TITLE
I want he creator of this mod update erebus to 1.10.2

### ISSUE THREAD

**Issue by Tiaaa04** [ganymedes01/TheErebus#566]
I don't know how to use the pull request and because of this i'll write in issues
Can the Creator of this mod create 1.10.2 version for minecraft? 
I don't want to make cry my childs and i want the creator make the version of minecraft 1.10.2 or 1.9.4 because my childs play minecraft mod in 1.10.2 but they want the erebus mod and i'l don't make they cry for 3 days reapetly

**Comment by vadis365** [comment]
Hello,
I'm sorry - here have a cute picture of a kitten to make up for the delay.
![cute-kitten](https://user-images.githubusercontent.com/6518708/29572087-1b4b7646-8753-11e7-8b45-73c78705dab4.jpg)
Cheers,
Me.

**Comment by vadis365** [comment]
In the process of working on a 1.12 instead, so be patient and one day it will exist again.
