### ISSUE TITLE
"Suggestion" Glider chestplate have elytra ability...

### ISSUE THREAD

**Issue by VioletWyvern** [ganymedes01/TheErebus#569]
At 1.9, Minecraft has elytras, it was a fun and useful item.
But i suddenly think about, why don't let's our glider chestplate has elytra's ability?  Just curious..... 
(Since elytra is a part of beetle's wings...)

**Comment by vadis365** [comment]
Maybe in the future - will re-visit when it has an overhaul.
Thanks for the suggestion.
