### ISSUE TITLE
Duplicate stat ID runtime exception

### ISSUE THREAD

**Issue by xAlicatt** [ganymedes01/TheErebus#571]
I have close to 300 mods, so I'm not surprised there's a conflict. Here's the crash report in any case: https://gist.github.com/xAlicatt/b5a1d652e9172fe8297452b7944f61c5

**Comment by Sunconure11** [comment]
Encountered the same issue. I believe it could be related to BoP.

https://pastebin.com/vPt02MpR

**Comment by vadis365** [comment]
Hello, it looks like the wasp from Erebus and the wasp from BOP have some conflicting code that tries to register the mobs with the same stat. Will investigate as this is baaaaaaaaaaad.

**Comment by vadis365** [comment]
will be fixed - need to change some things, build and re-upload to curse, because this is something stupid that will probably happen with other mods if mobs have the same name.
thanks for the report :)

**Comment by vadis365** [comment]
Approved on curse - closing this issue, please open an new issue if you have any other problems :)
