### ISSUE TITLE
Crash with Biomes O Plenty/3D Item Models Dont Show up

### ISSUE THREAD

**Issue by ghost** [ganymedes01/TheErebus#572]
i tried to load up the 1.12 version that was just released in my mod pack but it crashed with Biomes O plenty.

As i tried the mod in the mod pack(after i removed biomes O Plenty) i recognized that the 3d item models don't seem to show up (im thinking its because of the betwenlands because it often breaks other 3d item models(but i don't know if its really the betweenlands))

i hope i could help

ps:sorry for my bad englisch

**Comment by vadis365** [comment]
Are you using optifine?

**Comment by vadis365** [comment]
BOP crash should be fixed in next version (uploading to curse as we speak) as for the rendering issue, I honestly don't know why that would happen, I would suggest testing without optifine if you are using it as I know that causes MANY mods to have rendering issues.

**Comment by vadis365** [comment]
Approved on curse - closing please open an new issue if you have any other problems :)
