### ISSUE TITLE
Crash [1.12.2]

### ISSUE THREAD

**Issue by Kocytos** [ganymedes01/TheErebus#573]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.0-core.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-77-core.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6 (1).jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.4.jar)
  FarseekCoreMod (Farseek-1.12-2.2.3 (1).jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10 (1).jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12 (2).jar)
  FMLPlugin (elulib-0.1.11 (1).jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 2/21/18 9:51 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Erebus (erebus)
Caused by: java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.wasp.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.wasp.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.wasp
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraft.stats.StatList.func_151182_a(StatList.java:305)
	at net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:450)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerEgg(EntityRegistry.java:220)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:171)
	at erebus.ModEntities.registerEntity(ModEntities.java:198)
	at erebus.ModEntities.registerEntity(ModEntities.java:194)
	at erebus.ModEntities.init(ModEntities.java:102)
	at erebus.Erebus.preInit(Erebus.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1318550296 bytes (1257 MB) / 3221225472 bytes (3072 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_C8 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                      | Source                                            | Signature                                |
	|:----- |:-------------------- |:---------------------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                       | minecraft.jar                                     | None                                     |
	| UCH   | mcp                  | 9.42                         | minecraft.jar                                     | None                                     |
	| UCH   | FML                  | 8.0.99.99                    | forge-1.12.2-14.23.2.2611.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.2.2611                 | forge-1.12.2-14.23.2.2611.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | elucore              | 1.0                          | minecraft.jar                                     | None                                     |
	| UCH   | mercurius_updater    | 1.0                          | MercuriusUpdater-1.12.2.jar                       | None                                     |
	| UCH   | aether_legacy        | 1.12.2-v2.0                  | aether_legacy-1.12.2-v2.0 (1).jar                 | None                                     |
	| UCH   | applecore            | 3.1.1                        | AppleCore-mc1.12.2-3.1.1.jar                      | None                                     |
	| UCH   | jei                  | 4.8.5.157                    | jei_1.12.2-4.8.5.157.jar                          | None                                     |
	| UCH   | appleskin            | 1.0.9                        | AppleSkin-mc1.12-1.0.9 (1).jar                    | None                                     |
	| UCH   | astikoor             | 1.0.0                        | astikoor-1.0.0.jar                                | None                                     |
	| UCH   | betterbuilderswands  | 0.11.1                       | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
	| UCH   | betterfoliage        | 2.1.10                       | BetterFoliage-MC1.12-2.1.10 (1).jar               | None                                     |
	| UCH   | bibliocraft          | 2.4.3                        | BiblioCraft[v2.4.3][MC1.12.0] (2).jar             | None                                     |
	| UCH   | biomesoplenty        | 7.0.1.2313                   | BiomesOPlenty-1.12.2-7.0.1.2313-universal (2).jar | None                                     |
	| UCH   | blockcraftery        | 0.1.3                        | blockcraftery-0.1.3 (2).jar                       | None                                     |
	| UCH   | campfire             | 1.2                          | campfire-1.12-v1.2 (1).jar                        | None                                     |
	| UCH   | ctm                  | MC1.12-0.2.3.12              | CTM-MC1.12-0.2.3.12 (2).jar                       | None                                     |
	| UCH   | chisel               | MC1.12-0.1.1.26              | Chisel-MC1.12-0.1.1.26 (1).jar                    | None                                     |
	| UCH   | chiselsandbits       | 14.14                        | chiselsandbits-14.14.jar                          | None                                     |
	| UCH   | codechickenlib       | 3.1.5.331                    | CodeChickenLib-1.12.2-3.1.5.331-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | customspawner        | 3.11.3                       | CustomMobSpawner-3.11.3.jar                       | None                                     |
	| UCH   | ptrmodellib          | 1.0.0                        | Decocraft-2.5.4_1.12.2.jar                        | None                                     |
	| UCH   | props                | 2.5.4                        | Decocraft-2.5.4_1.12.2.jar                        | None                                     |
	| UCH   | mocreatures          | 12.0.3                       | DrZharks MoCreatures Mod-12.0.3.jar               | None                                     |
	| UCH   | dsurround            | 3.4.9.4                      | DynamicSurroundings-1.12.2-3.4.9.4.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | presets              | 3.4.9.4                      | DynamicSurroundings-1.12.2-3.4.9.4.jar            | None                                     |
	| UCE   | erebus               | 1.0.17                       | Erebus-1.0.17.jar                                 | None                                     |
	| UCH   | exoticbirds          | 1.0                          | Exotic+Birds+1.12.2-1.4.0.jar                     | None                                     |
	| UCH   | farseek              | 2.2.3                        | Farseek-1.12-2.2.3 (1).jar                        | None                                     |
	| UCH   | foragecraft          | 1.14.2                       | foragecraft-1.14.2 (2).jar                        | None                                     |
	| UCH   | glitchcore           | @MOD_VERSION@                | GlitchCore-1.12.2-1.0.0-universal.jar             | None                                     |
	| UCH   | gravestone           | 1.10.1                       | gravestone-1.10.1.jar                             | None                                     |
	| UCH   | waila                | 1.8.23                       | Hwyla-1.8.23-B38_1.12 (2).jar                     | None                                     |
	| UCH   | llibrary             | 1.7.9                        | llibrary-1.7.9-1.12.2.jar                         | None                                     |
	| UCH   | iceandfire           | 1.3.1                        | iceandfire-1.3.1-1.12.2 (2).jar                   | None                                     |
	| UCH   | mantle               | 1.12-1.3.1.21                | Mantle-1.12-1.3.1.21 (2).jar                      | None                                     |
	| UCH   | tconstruct           | 1.12.2-2.9.0.55              | TConstruct-1.12.2-2.9.0.55 (1).jar                | None                                     |
	| UCH   | immersiveengineering | 0.12-77                      | ImmersiveEngineering-0.12-77.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | inventorytweaks      | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | jjcoa                | 1.0.9                        | JJ+Coats+of+Arms+1.12-1.12.2-v1.0.9.jar           | None                                     |
	| UCH   | journeymap           | 1.12.2-5.5.2b1               | journeymap-1.12.2-5.5.2b1.jar                     | None                                     |
	| UCH   | customnpcs           | 1.12                         | Kocytos NPCs.jar                                  | None                                     |
	| UCH   | levelup2             | ${version}                   | Level+Up!+2-1.1.15-1.12.jar                       | None                                     |
	| UCH   | malisiscore          | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| UCH   | malisisblocks        | 1.12.2-6.1.0                 | malisisblocks-1.12.2-6.1.0.jar                    | None                                     |
	| UCH   | malisisdoors         | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| UCH   | naturescompass       | 1.5.1                        | NaturesCompass-1.12.2-1.5.1 (1).jar               | None                                     |
	| UCH   | ordinarycoins        | 1.3.1                        | ordinarycoins-1.3.1 (1).jar                       | None                                     |
	| UCH   | harvestcraft         | 1.12.2p                      | Pam's+HarvestCraft+1.12.2p.jar                    | None                                     |
	| UCH   | placeableitems       | 3.2                          | placeableitems-3.2 (1).jar                        | None                                     |
	| UCH   | shetiphiancore       | 3.5.6                        | shetiphiancore-1.12.0-3.5.6 (1).jar               | None                                     |
	| UCH   | platforms            | 1.4.4                        | platforms-1.12.0-1.4.4.jar                        | None                                     |
	| UCH   | signpost             | 1.07.1                       | signpost-1.12-1.07.1.jar                          | None                                     |
	| UCH   | streams              | 0.4.2                        | Streams-1.12-0.4.2 (1).jar                        | None                                     |
	| UCH   | thebetweenlands      | 3.3.0                        | TheBetweenlands-3.3.0-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCH   | corerm               | 1.2h                         | TheCampingMod_2.3g.jar                            | None                                     |
	| UCH   | camping              | 2.3g                         | TheCampingMod_2.3g.jar                            | None                                     |
	| UCH   | twilightforest       | 3.6.345                      | twilightforest-1.12.2-3.6.345-universal.jar       | None                                     |
	| UCH   | wailaharvestability  | 1.1.12                       | WailaHarvestability-mc1.12-1.1.12.jar             | None                                     |
	| UCH   | wearablebackpacks    | 3.1.2                        | WearableBackpacks-1.12.2-3.1.2.jar                | None                                     |
	| UCH   | elulib               | 0.1.11                       | elulib-0.1.11 (1).jar                             | None                                     |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.0-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-77-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6 (1).jar)
  shetiphian.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.4.jar)
  org.blockartistry.DynSurround.asm.Transformer
FarseekCoreMod (Farseek-1.12-2.2.3 (1).jar)
  farseek.core.FarseekClassTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10 (1).jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12-0.2.3.12 (2).jar)
  team.chisel.ctm.client.asm.CTMTransformer
FMLPlugin (elulib-0.1.11 (1).jar)
  elucent.elulib.asm.ASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 760/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by vadis365** [comment]
Closing this as it's the same issue as #571 - will deal with it in 1 place

**Comment by vadis365** [comment]
should be good now - released a fix - thanks for the report :)
