### ISSUE TITLE
3D Item Model Rendering Issue with Botania

### ISSUE THREAD

**Issue by ghost** [ganymedes01/TheErebus#576]
It seems like botania somehow has a problem with erebus and is causing this issue(i dont know how).
(yes i tested it without optifine)
i watched a bit trough your code and i looked at the item models and i have a question the only 3d models i found where the ones from the shields and they don't seem to have a texture dependency so maybe that is the reason .

I used :
Botania (r1.10-353)
Baubles(1.12-1.5.2)
Erebus(1.0.18)

**Comment by Sunconure11** [comment]
I'm seeing invisible shields as well.

**Comment by ghost** [comment]
that is what i meant with 3d item models

**Comment by Sunconure11** [comment]
I'm noticing it's starting to extend to things like the web slinger, as well.

**Comment by vadis365** [comment]
OK, added some gl code to reset the render state to all the custom item models. Botania is not the only mod the Erebus isn't working well with for this issue. Will test the mod in a new instance and see if it is still happening.

**Comment by vadis365** [comment]
Should be fixed in next release \o/

**Comment by Sunconure11** [comment]
I'm still encountering this.

**Comment by Sunconure11** [comment]
Still present as of the Third of May in 2018.

**Comment by vadis365** [comment]
#619
