### ISSUE TITLE
ItemBlockEnum.getUnlocalisedName assumes that the stack is valid.

### ISSUE THREAD

**Issue by AlexIIL** [ganymedes01/TheErebus#577]
Specifically [here](https://github.com/ganymedes01/TheErebus/blob/mc1.12/src/main/java/erebus/items/block/ItemBlockEnum.java#L29) -- the stack given may have a metadata outside of the array's size, however the method currently takes this and uses it directly for the array index. The original report is BuildCraft/BuildCraft#4047.

**Comment by vadis365** [comment]
That method is purely used as internal method to return an itemstack's name for enumerated block states. It "shouldn't" really ever produce anything outside the range of the blocks own internal states. I don't know the specific implementation used in BC that would be needing the itemstack's name from the blockstate but I'm guessing it is something to do with automagically creating facades.

**Comment by vadis365** [comment]
I can put an check in to stop the error and have also spoken to The Betweenlands mod as we use a similar implementation there - but BC should probably have something on their end to prevent any other issues with other mods and just "blindly assume" every mod will work fine :P
Thanks for the heads up - will sort out a compat fixy.

**Comment by AlexIIL** [comment]
We call `stack.getDisplayName()` rather than `getUnlocalizedName()` directly, however vanilla eventually calls your method anyway. (We use this for getting the localised name for a facade, so I'm not sure what else we could do)

Something else has obviously gone wrong though, as in theory we shouldn't have created an itemstacks outside of the valid range - it would probably be very useful to return an obviously wrong name (like "ERROR: Unknown metadata) so that we can look into what might be causing this.

**Comment by vadis365** [comment]
There are only probably half a dozen blocks or so that have metas up in that range so it shouldn't be difficult to find the culprit if it is something in Erebus.

**Comment by vadis365** [comment]
Fixed in the next update.
