### ISSUE TITLE
[1.12.2] Spawners aren't working

### ISSUE THREAD

**Issue by wamc2017** [ganymedes01/TheErebus#579]
Hi,

thanks for updating to 1.12.2, played your mod a bit yesterday and besides the model problem with Botania installed (mentioned in #576) I found another thing.

None of the spawners is working, they got a pig in it (also TOP mentions those are pig spawners) and nothing spawns near them. Maybe this has something todo with the BoP bugfix, because they worked fine in version 1.0.17. Tried it with only this mod installed, so it should be not an issue with compatibility... :smile:

Versions:
Minecraft: 1.12.2
Forge: 14.23.2.2618
Erebus: 1.0.19 (maybe also 1.0.18)

Thanks for looking into it.

Kind regards
wamc

**Comment by vadis365** [comment]
Hello,
Thanks, yeah, it's because of the BOP fix - I must have forgotten to update the spawners to the new mob names - will fix ASAP
Cheers,
Me.

**Comment by vadis365** [comment]
Closing as this is fixed in the 1.0.20 update.
