### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Divineaspect** [ganymedes01/TheErebus#582]
https://pastebin.com/SDVaVXJd

**Comment by vadis365** [comment]
Hello,
Can you check your configs folder and see if there is actually a file called ErebusEntityDimensions.cfg ?
It is where the user editable render scaling for modded mobs goes, to edit entities preserved using the wand of preservation. The basic file generated by Erebus contains no information other than example for the minecraft cow - but will throw an exception if the file is not present or errored.
Cheers,
Me.

Edit - the mod is also built against Forge 1.12.2-14.23.2.2611
You are running 1.12.2-14.23.1.2607 in that crash report so I would suggest also updating.

**Comment by Divineaspect** [comment]
doesn't seem to be that file. Have verified that something was corrupted 
I've updated forge, and it's all shiny now. Thanks!
