### ISSUE TITLE
[1.12.2] Bamboo Extender block missing particles crashes the server

### ISSUE THREAD

**Issue by NotAVerb** [ganymedes01/TheErebus#583]
Trying to destroy a bamboo extender crashes the server the moment a particle tries to appear.

**Comment by vadis365** [comment]
I cannot replicate this in testing.
It breaks fine for me redstone powered and unpowered, I have 'tweaked' the method where the block breaking is called for the next release, hopefully it will help your issue. Closing for now, will revisit if it's reported again in the future.
