### ISSUE TITLE
Rhino beetle Horn

### ISSUE THREAD

**Issue by SimulatorSia** [ganymedes01/TheErebus#584]
How does one get the Rhino beetle horn? It's not a drop from the bug when you kill it and it's not on the wiki. https://ftb.gamepedia.com/Titan_Beetle

Plus it says the Rhino Beetle drops exoskeleton plates which isn't true.

(1.12.2)

**Comment by vadis365** [comment]
Hello,
The code says it IS a drop - but it's a 1:20 chance.
https://github.com/ganymedes01/TheErebus/blob/mc1.12/src/main/java/erebus/entity/EntityRhinoBeetle.java#L177
The wiki is a little outdated here and there, but in time things will be fixed.
Cheers,
Me.

**Comment by SimulatorSia** [comment]
Ty, I'll keep farming. Don't mean to be trouble. Thanks for answering
