### ISSUE TITLE
[1.12.2] Planticide problems

### ISSUE THREAD

**Issue by DaedalusGame** [ganymedes01/TheErebus#588]
- Right now if you apply Planticide to a modded block with the grass material it will poof the block completely instead of placing a dirt-variant down. This is actually a bit more complicated to solve because blocks don't really return a block they would like to turn into internally, but I think a config could be created for support.
- Planticide does not destroy fully-grown pumpkins and melons (this may be a design choice but pumpkins and melons are plants after all)
- Planticide will "stir up" coarse dirt. By this I mean that it will turn coarse dirt into coarse dirt and spits out some particles, possibly because coarse dirt has the grass material? This isn't really a big problem just a small consistency thing.

**Comment by vadis365** [comment]
Will look at doing something about this in the future Bord. For the time being it'll remain as it is.
