### ISSUE TITLE
[1.12.2] bucketHoney contains all forge buckets and bambuckets

### ISSUE THREAD

**Issue by DaedalusGame** [ganymedes01/TheErebus#589]
Instead of just buckets containing honey, this oredict entry (i think it is created by erebus) contains every forge bucket and bambucket. Other modded buckets (eg clay buckets from ceramics) are not affected.

**Comment by vadis365** [comment]
Hello,
Ah, whoops, the bucket code was completely changed and I guess I missed that in the code.
Thanks for pointing it out, I'll fix it in the next release (for now, it'll just have to be a bit annoying - sorry).
Cheers,
Me.

**Comment by vadis365** [comment]
disabled them from ore dict - will leave them disabled for now as the universal buckets make it tricky.

**Comment by DaedalusGame** [comment]
yepp, the oredict can't hold nbt and for some reason nobody has been bothered by it for several years
