### ISSUE TITLE
[1.12.2][1.0.22] Crash when clicking the recipe book

### ISSUE THREAD

**Issue by DylanGK** [ganymedes01/TheErebus#590]
https://pastebin.com/GTP2Et3J

I get the following crash when clicking on the vanilla recipe book, 100% reproduction rate.

**Comment by vadis365** [comment]
![clicky](https://user-images.githubusercontent.com/6518708/37628001-171dfb72-2bcf-11e8-9c1f-ac965c9c7a65.gif)

**Comment by DylanGK** [comment]
Odd, I will see what mod causes it then. I was drawn here because the crash log specifically mentioned an Erebus recipe.

**Comment by artumino** [comment]
I get the same problem on a fresh Sponge+Forge server with this crash log:

`Error: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: erebus.recipes.RecipeSprintLeggingsUpgrades@68b793f9 Name: erebus:leggings_upgrades`

I can only reproduce this in multiplayer though.
No other mods are installed apart from the Sponge 7.1.0 framework.
