### ISSUE TITLE
Suggestion: configurability of what fluids Bambuckets and Fluid Jars can hold

### ISSUE THREAD

**Issue by DylanGK** [ganymedes01/TheErebus#592]
I think having it configurable would serve 2 purposes that I think are important:

- Some more realism. Buckets made out of Bamboo shouldn't be able to pick up Acid or Lava, right?
- Another tool for modpack creators. 

I am not sure how hard this would be to implement, but I think we should keep it in mind.

**Comment by vadis365** [comment]
I can disable lava and acid easy, I just left them in for no other reason than the buckets were a pain to port and I couldn't remember is we allowed it or not - lol
