### ISSUE TITLE
Suggestion: Bamboo piping improvements

### ISSUE THREAD

**Issue by DylanGK** [ganymedes01/TheErebus#593]
* Redstone functionality for the Extraction pipe. I can see a case for keeping it at least semi-manual though. Would love to hear thoughts.
* Bamboo pipes only connect to eachother when the ''ends meet''. So the input part only connects to a different pipes output part and vice versa.
* Improved logic? There's some weird cases going on, for example, prioritisation of where the fluid goes when the fluid has 2 ways to go does not seem to have any intuitive logic behind it, but perhaps I need to learn about the existing logic better.

**Comment by vadis365** [comment]
Yeah, it's a 'dumb' piping system that doesn't use a network for the logic, it's not really intended for complex stuff tbh, there are much better mods out there you should use for fluid piping - this feature was just added to make Erebus things a little easier. I'll look at making a better system in the future, but I'm ok with it being ghetto for the time being - redstone activation should be easy to implement for the extraction pipe and is a good idea. Going to close, but have added this to my 'things to improve' list. :)
