### ISSUE TITLE
Crash when clicking the recipe book (only with dedicated server)

### ISSUE THREAD

**Issue by Jacky10X** [ganymedes01/TheErebus#597]
it is exactly same as
this issue 
https://github.com/ganymedes01/TheErebus/issues/590
since you close it 
i just open another one
it is the same log when you open recipe book
https://pastebin.com/GTP2Et3J same as issues 590
it is happened when you joining dedicated server like forge server, spongeforge
if you are singleplayer
it won't have this problem

**Comment by Jacky10X** [comment]
So do someone know what is going on?
it seem it happened when you joining the dedicated server like forge server, spongforge (Not happen in singleplayer)

**Comment by vadis365** [comment]
Should be fixed in next update - I think it was a derp on the recipe registry.
Thanks for the report.
