### ISSUE TITLE
Erebus Sub-biomes in Config

### ISSUE THREAD

**Issue by EverSoul** [ganymedes01/TheErebus#598]
I am using the latest version of The Erebus for 1.7.10.

I just wanted to say that the sub-biomes are not in the configs, so I have no way of changing their IDS.

**Comment by vadis365** [comment]
Hello, yeah, that is something that was never addressed.
The 1.7.10 version is no longer an active development version and hasn't been for 2 years.
Closing due to (sorry) outdated.
