### ISSUE TITLE
Top of Bullrush places as two parts

### ISSUE THREAD

**Issue by Divineaspect** [ganymedes01/TheErebus#605]
This means that infinite papyrus is just a few clicks away

**Comment by vadis365** [comment]
I'm unsure as what you mean here. The bullrush will break the block and drop papyrus or if sheers are used the plant drops.
The plant is the same as any other double height plant and if bone meal is used will give you more.

**Comment by Divineaspect** [comment]
if you attempt to break the top part it breaks off, when placed it generates the two high plant immediately.

**Comment by vadis365** [comment]
I still don't see the issue here?
The plant will break and only drop papyrus.
If shears are used it drops the block, yes and is plantable, yes, the same as vanilla double high plants.

**Comment by Divineaspect** [comment]
It doesn't grow, it just only appears as the two high plant, and it doesn't require shears.
