### ISSUE TITLE
Unable to activate portal

### ISSUE THREAD

**Issue by UnixRonin** [ganymedes01/TheErebus#606]
Just installed Erebus for the first time (Erebus-1.0.22, 1.12.2, forge-1.12.2-14.23.3.2655)
Verified I have a DIM66. Check.
Made an offering altar. Check.
Made a Gaean Stone. Check. (I love the crafting effect!)
Made a Staff of Gaea. Check.
Made a Gaean Keystone. Check.
Built a portal. Check. Filled it with vanilla oak leaves. Nothing overly fancy, no bizarre shape, all continuous, all vanilla stone bricks.
Placed the keystone in front of it. Check.

Right-click the keystone with the Staff of Gaea. **Nope. Can't do it. Nothing happens.**
Tried shift-right-clicking, too. That doesn't work either. Server console shows no error messages.

Am I doing something wrong? Did I miss something? Is my keystone too far from my portal? (2 blocks away, directly in front of the center) Is my portal too big, too small? The CurseForge overview says it can be any size and shape.

Screenshot:
[https://www.caerllewys.net/public/minecraft/Erebus-portal.png](url)

Subsequently I've tried reshaping the portal to make the bottom row only 3 blocks wide.  Making the _entire portal_ only 3 blocks wide.  Clearing up the dry leaves in front of the portal. Moving the keystone closer.  Moving the keystone further away.  Moving the keystone **right in front** of the portal.  Nada.  No joy.  Nothing works.

**Comment by UnixRonin** [comment]
Solved, eventually:
There must be absolutely **NOTHING** within two blocks clear **BEHIND** the portal, or the portal will not form.

**Comment by vadis365** [comment]
OK then.
Thanks for the report, I'll look in to it and see about either changing that or at least documenting it somewhere with clearer instructions on the portal.

**Comment by UnixRonin** [comment]
I don't think it needs to be changed, just so long as it's documented.
