### ISSUE TITLE
Savannah is too green

### ISSUE THREAD

**Issue by DylanGK** [ganymedes01/TheErebus#607]
The Savannah's grass colour seems to have changed, making the Savannah all too green and making it resemble a savannah far less. Somewhat more brownish might suit it better?

**Comment by vadis365** [comment]
1.7.10 colour setting: setColors(0xB6B957, 0xA3A52D);
1.12.2 colour setting: setColors(0xB6B957, 0xA3A52D);

The game itself may have some other rendering/colour/lighting stuff going on or something, but the code is exactly the same in both Erebus versions.

**Comment by vadis365** [comment]
um, I guess this is moot then.
