### ISSUE TITLE
Tweak:  Can the "solidity" of the Block o'Bones be reduced?

### ISSUE THREAD

**Issue by UnixRonin** [ganymedes01/TheErebus#610]
The Block o'Bones is, I think, probably the best-looking gravestone feature I've seen.  However, it has just a slight drawback:  In combination with mods (such as Journeymap) or server-side features that allow you to teleport back to your death mod, it results in you teleporting back **inside your block o'bones** and immediately dying again.

Could the Block o'Bones be perhaps made a little less solid?  Or perhaps teleporting back inside your Block o'Bones could break the block instead of killing you a second time?  So far,on my newly-regenerated server, my leading cause of death is my own gravestone.  I had to turn it off for now.

**Comment by vadis365** [comment]
Hello,
Changing the mechanics is a tricky one as it's not really meant to be used with teleporting mods etc - but I have made it so the block no longer causes suffocation damage in the next update.
I'll look in to changing some of the mechanics one day soon.
Cheers,
Me.

**Comment by UnixRonin** [comment]
Making it not suffocate is **fine**.  :)  Thank you!
