### ISSUE TITLE
Game Breaking Crash on player death

### ISSUE THREAD

**Issue by JimMiningWorm** [ganymedes01/TheErebus#611]
In a 1.12.2 mod pack, I was getting an intermittant game breaking crash when dying. Tried the usual removing optifine, foamfix etc. Eventually tracked it down to Erebus. It happens when the player is killed, but only under certain conditions: basically you need to be killed by mobs (zombies or spiders for example) whilst they are pushing you against some blocks. Dying by falling to your death for example does not produce the crash, nor does being killed by mobs when you are in open space.

Took a while to figure out, but here's how to reproduce, with just Erebus (and forge) installed:
- place some blocks around you, so that you are pushed against them (in the overworld).
- spawn in some zombies and spiders
- wait for them to kill you, ensuring they are pushing you against those blocks
- As soon as you die, it will crash.

Crash log: https://pastebin.com/a0tnTRg7

Although the crash log is not particularly helpful - the stack trace contains no references to any erebus files or classes.

I suspect its either the placing of the Block o' Bones, or the death compass. The crash in my modded world referenced renderHand in its crash log, so maybe its the compass

Heres the crash log from my other world, with other mods installed: https://pastebin.com/7UCzV9Fv

Other info:
SSP, 1.12.2, on linux
forge: 1.12.2-14.23.3.2655
Erebus: 1.0.22

Let me know if you need any more information.

**Comment by vadis365** [comment]
Hello,
I managed to replicate the bug as you say. It should be fixed now, seems it was related to the rendering of the block of bones somehow O.o 
Should be fixed in next update.
Cheers,
Me.
