### ISSUE TITLE
porting in

### ISSUE THREAD

**Issue by Caedus-Renegade** [ganymedes01/TheErebus#612]
if you're on a superflat map and the height is above 128 - it teleports you up in the air and you fall until you die
this happens with dimensions using the Nether as a base

**Comment by VioletWyvern** [comment]
This also affect on superflat map and the height is under 5 - You will spawn in the rocks and gets suffocated...

**Comment by vadis365** [comment]
Yeah, the Erebus portal logic is a little screwy with height checks for superflat - it is a port of some old 1.7.10 code that was never made to be 100% safe. I'll look in to changing some things when the next round of updating the portal logic is done (other things need to be changed too) but that will probably involve a re-coding of the logic and as such may not be done for the next release, but definitely soon TM.
Going to close this for now as it is noted as a fix but not critical, but does need addressing.
Cheers,
Me.
