### ISSUE TITLE
Client crashes when attempting to join the server

### ISSUE THREAD

**Issue by belathus** [ganymedes01/TheErebus#613]
https://paste.dimdev.org/jikikimoku.txt

I'm able to join a singleplayer world just fine. Another player was able to join the server, though, so I'm not sure what is going on.

**Comment by belathus** [comment]
Restarting the client fixed it, but... that's odd. I literally just started before, and I wasn't the only one affected.

**Comment by vadis365** [comment]
Should be fixed in the next update. I'm hoping this was just a derp on some registry stuff.
