### ISSUE TITLE
Odd problem with Block O'Bones: some of the ones I place are invisible?

### ISSUE THREAD

**Issue by DylanGK** [ganymedes01/TheErebus#615]
I've no clue how this happens, but I placed some of the Block O'Bones from creative and, well, this is what happened:

![2018-05-17_11 40 50](https://user-images.githubusercontent.com/5971389/40169897-5d0ac6e4-59c7-11e8-904e-54a88ff2aff5.png)

**Comment by vadis365** [comment]
No idea O.o
I can't duplicate this in any world I have tested in - will look in to it, but it's a weird one.
going to close as it's noted, but not a critical thing atm.
