### ISSUE TITLE
Crash upon encountering Stag Beetle

### ISSUE THREAD

**Issue by LordAlbatross** [ganymedes01/TheErebus#617]
Crash Report:
https://pastebin.com/RRDZCg4e
Seems to be whenever a stag beetle is loaded, immediately crashes everyone in the vicinity. Encountered in Multiplater.
EDIT: Encountered in the 1.12.2

**Comment by vadis365** [comment]
Hello,
I'll look in to this, It is a something new that hasn't cropped up before. All the mounts worked fine in testing on a server when the mod was ported, but there may be something wonky or an edge case I don't know about.
Cheer,
Me.

**Comment by vadis365** [comment]
Fixed in dev.
Closing as the next release will have this sorted.
