### ISSUE TITLE
Endless Traverse screws up rendering of 3D items in this mod

### ISSUE THREAD

**Issue by Sunconure11** [ganymedes01/TheErebus#619]
![screenshot 2018-06-04 17 12 29](https://user-images.githubusercontent.com/5614902/40941923-824432c2-681a-11e8-809c-79acda9b50d3.png)

**Comment by vadis365** [comment]
Hello,
I have no idea what is making this happen for you, the previous cause was something conflicting with botania's rendering. I can run both botania and baubles with Erebus and don't have the issue. I'm really not sure what mod conflict could be causing this for you. I suggest doing a binary search for your mods and finding out. I'll see if it can be sorted if I know what mod is making this magic happen.
Cheers,
Me.

**Comment by Sunconure11** [comment]
I am not sure what mod is causing this TBH, but I can give you something that can probably help, my modpack, in curse pack form.

https://www.dropbox.com/s/amfrhemc28xzu7x/CM%201.12.2-erebus-bugfixing.zip?dl=0

**Comment by Sunconure11** [comment]
Try sorting through that when you can, it's a big pack though. I haven't the foggiest of clue as to where to start, so I'm not sure where the rendering error lies.

**Comment by Sunconure11** [comment]
While starting the binary search, I found this in the logs.

https://pastebin.com/SLWdAuE9

Edit 1: This binary search is going to take some time, due to the size of my modpack. But would it be feasible to rewrite shield and tool rendering to be more in line with other mods that have 3D tools (i.e the betweenlands, gravestones extended, etc), or at least, see how they are doing it, so the mod is less likely to run into this issue?

Edit 2: I am too burnt out just by trying to go through all of my mods to continue the binary search. Furthermore, there are a few other bugs in my game from other mods I'm waiting on fixes for that are eating up a bit of my time as well, burning me out further.

**Comment by AlexModGuy** [comment]
@Sunconure11 do you use Optifine by chance?
In versions before D3 Items uing custom TEISRs were invisible. This was fixed in D3. Erebus has 
>	ForgeHooksClient.registerTESRItemStack(ModItems.BAMBOO_SHIELD, 0, TileEntityBambooShield.class);
in its ClientProxy.

check and see if this is an optifine issue.

**Comment by vadis365** [comment]
It doesn't actually - people keep reading the 1.9 code (I cant change the master branch - it's not my repo)
https://github.com/ganymedes01/TheErebus/blob/mc1.12/src/main/java/erebus/proxy/ClientProxy.java#L365
Is where the shields are registered now - but yeah, it's still a TESR itemstack in reality. ;)

**Comment by AlexModGuy** [comment]
whoops lol

anyways that only works as more proof that its on optifines side.
see https://github.com/Alex-the-666/Ice_and_Fire/issues/753

**Comment by Sunconure11** [comment]
I am not using Optifine. Foamfix, BetterFPS, VanillaFix, and a few other such mods are installed, but not Optifine.

**Comment by AlexModGuy** [comment]
remove them one by one and find which one is causing it

**Comment by Sunconure11** [comment]
I was working towards it but got burned out from numerous things. Will try again tomorrow.

**Comment by Sunconure11** [comment]
https://pastebin.com/9B3R85pU

While I haven't found the culprit yet, I found some more things in the logs. I'm trying to see if the logs would show anything

**Comment by Sunconure11** [comment]
Culprit has been found. Endless Traverse is to blame.

https://minecraft.curseforge.com/projects/endlesstraverse

**Comment by vadis365** [comment]
Closing because it's not us this time \o/.
