### ISSUE TITLE
Death compass spawning aimed at 0,0  (1.12.2 version)

### ISSUE THREAD

**Issue by Winddbourne** [ganymedes01/TheErebus#622]
For some reason the death compass is always spawning aimed at 0,0 in the over world.  

The death version from the spin off (stand alone) mod is working fine with my pack, but there is no configuration option to stop the player from receiving the busted one . . . so right now when players die in my pack they are receiving a busted death compass, a working death compass, and the inventory list from Tomb Many Graves.

It's a minor bug, but annoying. I'd really like to at least have the option of turning off the busted compass. lol

**Comment by vadis365** [comment]
Hello,
If you are using Tomb Many Graves then you have no need for the Erebus block o'bones grave, there is a config option to turn the block o'bones grave off, which will also stop the player gaining an Erebus death compass.
Cheers,
Me.

**Comment by Winddbourne** [comment]
thanks :)

**Comment by vadis365** [comment]
Hello,
I will be porting over the code from the standalone mod to Erebus as the 2 code bases are different atm, this will probably make the Erebus compass work correct again.
Closing as this is something that will be fixed in the next release.
Cheers,
Me.
