### ISSUE TITLE
FTBs /Back command

### ISSUE THREAD

**Issue by ghost** [ganymedes01/TheErebus#626]
Forge 2712
MC 1.12.2
The Erebus 1.0.22

So when I die the grave from Erebus shows up. good.. when I respawn and use FTB's /Back command, I teleport to where I died but I get an instant MC Crash.  the error report is below - pretty generic really

https://pastebin.com/NdaWixsY

It doesnt happen when Erebus is removed from ModPack

FTB said he cant do anything about it because error is so generic

Is this something you can fix?

**Comment by vadis365** [comment]
Yeah, that is a weird one, there will be an update to Erebus with a lot of fixes very soon. I'm going to close this for now as it is too difficult to say what that could be. Please open a new issue if this happens with a newer version when it is released.
