### ISSUE TITLE
Larva Wheel (for Dave too)

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#63]
The Larva Wheel is a 3D modelled cool block thing.

http://i.imgur.com/03CuQRm.png

You can pipe in wooden items (it has an internal inventory of 3 slots). The Wooden Items make the Larva run (anything materialWood). They fuel him for as long as they would burn in a furnace.

It produces 10 RF per tick.

The wheel should be animated, and the larva inside it too. It should overall just look like it's a busy thing. Add some squeecky wheel sounds, larva fapping and squishing, and woodnomming, and you've got yourself a loud engine.

It has no internal buffer for RF. Any RF that isn't piped anywhere will be lost. It is not smart enough to stop using fuel when the produced power has nowhere to go. It's a larva after all. He'll keep trying to eat it.

**Comment by vadis365** [comment]
Bye-bye idea... not for this mod anymore...
