### ISSUE TITLE
While trying to diagnose and resolve an unrelated error, I found something odd going on with your mod

### ISSUE THREAD

**Issue by Sunconure11** [ganymedes01/TheErebus#630]
https://github.com/Buuz135/Thaumic-JEI/issues/29

Ctrl + F "32767"

**Comment by Zer0Lyfe** [comment]
not just @Sunconure11 either
https://gist.github.com/Zer0Lyfe/81e4332fc7ab8a9f7568e632afd29c3b

**Comment by vadis365** [comment]
Fixed in dev.
Closing as the next release will have this sorted.
