### ISSUE TITLE
Apply For Authorization

### ISSUE THREAD

**Issue by GingleMeow** [ganymedes01/TheErebus#634]
(Sorry,English is not my mother language,so I can't speak English very well:)
Hello!
Minecraft players in China like your mod very much. Someone likes to use your mod,The Erebus.But they couldn't download it.What a pity!So I want to apply for downloading authorization at mcmod.cn in China.
Thank you.

**Comment by vadis365** [comment]
Hello,
I would rather you did not post the mod on another site please. The curseforge website is the only legal place that the mod is available from. As I understand from other Chinese users, the curseforge site is available and accessible to them. I have had other requests from Chinese players to re-post the curseforge link which is the only permission I will grant. Other than that I'm sorry but no.
Cheers,
Me.
