### ISSUE TITLE
Feature Request: Advancements

### ISSUE THREAD

**Issue by KollinsPlays** [ganymedes01/TheErebus#637]
This looks like a fun mod. Any chance of adding Advancements and/or a manual that at least lead you into making the portal?

**Comment by vadis365** [comment]
Some proper advancements would be a great thing to add. It's all done with resources now so it's easily implemented by the creative team. :P

**Comment by vadis365** [comment]
Just waiting for some one to do them.
https://github.com/skylinerw/guides/blob/master/java/advancements.md

**Comment by DylanGK** [comment]
Currently being worked on, expect it to be added in the nearest update.

**Comment by DylanGK** [comment]
Closing this issue since Advancements have been added, including the requested portal guide.
