### ISSUE TITLE
Crash when breaking bamboo extender

### ISSUE THREAD

**Issue by MarioSMB** [ganymedes01/TheErebus#644]
I tried to break the bamboo extender with an axe from the BetweenLands mod (unsure if tool matters), and the game crashed:

Error: java.lang.RuntimeException: Missing particle!

Crash report: [https://paste.ubuntu.com/p/phBNgkKzFk/](url)

**Comment by MarioSMB** [comment]
This happens with any tool.

**Comment by vadis365** [comment]
Hello,
Fixed in dev. Thanks for the report.
Cheers,
Me.
