### ISSUE TITLE
Bamboo bridge hitbox takes up entire block

### ISSUE THREAD

**Issue by MarioSMB** [ganymedes01/TheErebus#645]
The bamboo bridge's hitbox (the lining around which you can hit it) takes up the entire block, which can make it awkward to break nearby blocks.

**Comment by vadis365** [comment]
Hello,
This is an awkward one to fix as the bounding boxes are particularly annoying to change. I have added a couple of vanilla methods (as per the other issue you posted) that may.
Cheers,
Me.
