### ISSUE TITLE
Mobs jump constantly when walking across bamboo bridges

### ISSUE THREAD

**Issue by MarioSMB** [ganymedes01/TheErebus#646]
This may be related to the hitbox issue, mobs see the bridges as full blocks and continuously jump while walking across them.

**Comment by MarioSMB** [comment]
Additionally, short mobs (spiders) take damage while on these bridges.

**Comment by vadis365** [comment]
Hello,
Suffocation is an easy fix and done in dev. The collision box of mobs means if they are 'on' the top they may jump about - it's a vanilla thing. I have added a couple of methods that may help.
Cheers,
Me.
