### ISSUE TITLE
wing suit causes world corruption when used.

### ISSUE THREAD

**Issue by EternalOne11** [ganymedes01/TheErebus#648]

**Comment by vadis365** [comment]
Hello,
Can you please post a log file of the crash report for the world in question?
I can't do anything with a title of an issue and nothing else to go on.
This is the 1st report EVER of this happening since the armour set was added (in 1.6X iirc).
Cheers,
Me.

**Comment by vadis365** [comment]
Hello,
No crash reports, no logs and no reply to me - guess what? Yup, closing issue, it's probably another mod or something, dunno.
Cheers,
Me.
