### ISSUE TITLE
[1.0.23] Crash with Astral Sorcery and Misty World

### ISSUE THREAD

**Issue by Rikshy** [ganymedes01/TheErebus#650]
forge: any
mc: 1.12.2
log: [crash log](https://paste.dimdev.org/bamonanoga.mccrash)

It crashes on world load! It will only crash if all 3 mods are present. I had it earlier this year with Harshen Universe instead of Misty World, but it got fixed on harshen side. Do you think this is an issue you could solve on yourside?

**Comment by vadis365** [comment]
Hello
This should actually be fixed in dev now.
If you still have the issue after the next Erebus update, please report again.
Cheers,
Me,
