### ISSUE TITLE
"Missing particle!" Crash when breaking Umber Golem Statue

### ISSUE THREAD

**Issue by lilypadlilith** [ganymedes01/TheErebus#655]
Client crashes with "java.lang.RuntimeException: Missing particle!" when trying to mine a placed Umber Golem Statue block. 

Minecraft Ver: 1.12.2
Erebus Ver: 1.0.23
Crash Report: [https://pastebin.com/SbNRdqaC](url)

**Comment by vadis365** [comment]
Hello,
Fixed in dev.
Will be in the next update.
Cheers,
Me.
