### ISSUE TITLE
Feature Request: Config option for the Advanced Homing Beecon

### ISSUE THREAD

**Issue by Shattered2909** [ganymedes01/TheErebus#656]
I am building a modpack and planning to make teleportation a thing for the very late game, but there is the Erebus in the earlier parts, could you do me a favor and add a config to disable the Advanced Homing Beecon?

**Comment by vadis365** [comment]
Hello,
If you are building a mod pack then you probably can just hide the item from JEI. I probably won't add a config for this sorry. The item could probably still generate in the dungeon chests it is coded to, unfortunately the loot for those is hardcoded atm and not working off the vanilla loot tables (will do when I get time for it). I will address this when I have more time and will reopen the issue.
Cheers,
Me.
