### ISSUE TITLE
[Suggestion] Bamboo pipes support Inspirations' cauldrons

### ISSUE THREAD

**Issue by wenlfs** [ganymedes01/TheErebus#657]
Bamboo pipes are only intented to work with Erebus' fluid tank? Because I tryed to use it with the Cauldrons modified by Inspirations that are fluid tanks and it doesn't work. Can you add some support?

Thank you!

**Comment by vadis365** [comment]
Hello,
The cauldrons you mention don't support the forge fluid capabilities and use vanilla methods.
If they did they would work  - I suggest asking the Inspirations dev to update his mod.
Cheers,
Me.
