### ISSUE TITLE
Umber Golem Statue crashes game when I break it!

### ISSUE THREAD

**Issue by Amborg22** [ganymedes01/TheErebus#658]
**Erebus version:** Erebus-1.0.23
**Minecraft version:** 1.12.2
**Forge version:** 14.23.4.2705
**Tinkers Construct version:** Mantle-1.12-1.3.2.24 / TConstruct-1.12.2-2.10.1.87

I obtained the umber golem statue and placed it in my home. attempted to break it using a manyllum pickaxe from _Tinker's Construct_ but when I simple left clicked it, my entire game froze and then crashed after a brief moment.

**Crash Report:** 
[crash-2018-10-28_18.02.24-client.txt](https://github.com/vadis365/TheErebus/files/2523311/crash-2018-10-28_18.02.24-client.txt)

NOTE: if you need files of every other Minecraft mod in my personal mudpack, please let me know.

**Comment by vadis365** [comment]
Hello, 
Fixed in dev and will be in the next update.
Cheers,
Me.
