### ISSUE TITLE
Gaea staff glitch 

### ISSUE THREAD

**Issue by palakasthetrue** [ganymedes01/TheErebus#659]
Version : Erebus-1.0.23

I found an infinite glitch for having gaea stuffs

[Erebus infinite staff glitch.zip](https://github.com/vadis365/TheErebus/files/2528968/Erebus.infinite.staff.glitch.zip)

**Comment by vadis365** [comment]
Hello,
Fixed in dev - will be in next update.
Cheers,
Me.
