### ISSUE TITLE
Compound goggles night vision do not work

### ISSUE THREAD

**Issue by Jack-0-Spades** [ganymedes01/TheErebus#661]
I was testing in creative to make sure mods I had were working correctly and I tried on the compound googles.  Both the regular and the reinforced versions give me the potion effect of night vision II, however I do not get the visual change. Potions of night vision still work as normal. I am not sure if maybe this is because Night vision II is not normally in the game.

**Comment by vadis365** [comment]
Hello,
I've tested both sets of goggles myself and they work in game for me.
You must have another mod effecting the way it works.
Sorry but I can't fix bugs that don't happen for me in testing.
Cheers,
Me,
