### ISSUE TITLE
No Return Portal

### ISSUE THREAD

**Issue by kmarple1** [ganymedes01/TheErebus#663]
Playing version 1.0.23. I got into Erebus just fine, but when I turned around, there was no return portal. I've been trying to build one, but it won't activate, so I assume the structure has to be different than the overworld one?

**Comment by vadis365** [comment]
Hello,
The portal 'can' sometimes be a little glitched on if it spawns a return structure.
I have tested and can make and activate return portals no problem.
One thing to note is; leaves sometimes mess up the portal block checking. I would try to build it away from where there are leaf blocks near (maybe just a couple of blocks away).
Cheers,
Me.

**Comment by kmarple1** [comment]
When I say no portal, I mean no portal at all. It's not glitched, nothing was generated at all. No leaves nearby; I spawned in an area full of umberstone.
