### ISSUE TITLE
Erebus Giant Flower Dyes

### ISSUE THREAD

**Issue by Cazadorsniper** [ganymedes01/TheErebus#665]
It looks like Erebus is interrupting the crafting of almost anything that needs dyes, like lapis blocks, bone blocks, and even the dye cluster in Mystical Agriculture.

Doesn't show the crafting in vanilla crafting table.
Does show in TConstruct and AE2 crafting station/terminal after closing the GUI then re-entering the GUI.

**Comment by vadis365** [comment]
Hello,
I'm going to go out on a limb here and say that the other mods are doing something and not Erebus.
The ONLY thing Erebus does with dyes is to ore dict the petal blocks so they can work as alias items for the vanilla dyes. I Repeat the ONLY thing is oredicting.
Cheers,
Me.

**Comment by Cazadorsniper** [comment]
Gonna try with Erebus by itself

**Comment by vadis365** [comment]
OK man.
On a side note there is now a blacklist for the WOA which you requested a bajillion years ago.
It's not meta sensitive tho' just for ease and the fact it'll all change in 1.13. :P 
Also some things are still left in as hardcoded Erebus/Blocks that were excluded before.
*Edit as default in the config there is minecraft:obsidian - remove or whatever.

**Comment by Cazadorsniper** [comment]
ok thanks and found the issue, it seems to be TConstruct lol

**Comment by vadis365** [comment]
well then.
Closing.

**Comment by Cazadorsniper** [comment]
found that erebus tconstruct and fastworkbench only cause this error if they're together.
Erebus + tinkers = error
Erebus + fastworkbench = error
any of the mods by themselves don't cause an issue

**Comment by Cazadorsniper** [comment]
ok it does seem to be Erebus for some reason.

**Comment by vadis365** [comment]
Now fixed. There was a single recipe that used dyes returning a null itemstack (legacy code) which was causing the whole issue. This may also be related to, and fix #603
