### ISSUE TITLE
making antivenom in the smoothie machine doesn't work as intended

### ISSUE THREAD

**Issue by lag42** [ganymedes01/TheErebus#670]
if you put a bucket or a bottle in the smoothie machine when making anti-venom you get 2 bottles of antivenom, if you put in a bambucket you get nothing

**Comment by vadis365** [comment]
This should be semi fixed in the next update - athough there is another bug with the Smoothie maker that means it consumes more items than it should if the same item required is in more than 1 slot - will fix that one another time.

**Comment by vadis365** [comment]
fixed in dev- I hope ;)
