### ISSUE TITLE
Issues with effects

### ISSUE THREAD

**Issue by SkyswordTK** [ganymedes01/TheErebus#672]
I am playing with some friends in FTB Infinity Evolved 1.7.10 and we also want to add The Erebus. Adding the mod itself actually works after changing some biome IDs but it keeps removing Thaumcrafts "Night Vision II" effect which is permanently applied by an enchantment on the helmet and i do not manage to find a way to prevent that. It actually causes the sky to keep flashing since it keeps beeing applied for 10 seconds, but is instandly removed. (And yes i did add and remove every other added mod and it always started happening after re-adding TheErebus)

**Comment by vadis365** [comment]
Hello,
Unfortunately the 1.7.10 version is no longer supported.
I do recall the bug being reported a few years ago.
I'm sorry but I don't think this will be fixed.
Cheers,
Me.
