### ISSUE TITLE
Tamed ants with shears stop working when MobGriefing set to false...

### ISSUE THREAD

**Issue by VioletWyvern** [ganymedes01/TheErebus#678]
Because some player didn't wants creepers blown up their home or endermens stealing their blocks, So they set MobGriefing to false to disable the destructions, But this also disable ants harvesting your mature crops (Because ant harvesting behavior was labeled for block griefing)

Maybe we can make ant harvesting behavior ignoring the MobGriefing command...

**Comment by vadis365** [comment]
I'll take a look and add a config option for this - I'd rather have both options available.

**Comment by vadis365** [comment]
ok - removed the mob griefing for this - not sure why it was there, but I guess it isn't needed ;)
fixed in dev.
