### ISSUE TITLE
mobs and cicadas

### ISSUE THREAD

**Issue by Inonedn** [ganymedes01/TheErebus#679]
currently, there is a bug when mobs can spawn ANYwhere, even behind the player or in their house, which is frustrating, and annoying. Secondly, cicadas sometimes permanently affect your sprint, unless you leave/rejoin while the nausea/slow icon is faded

**Comment by vadis365** [comment]
Will take a look, although the potion effects the cicadas give you have never done that before.

**Comment by vadis365** [comment]
The spawning seems fine to me and I can't duplicate the potion effect bug you are having.
As such I'll close this and re-open if others report the same issue with better explainations.
