### ISSUE TITLE
Unique crate functionality suggestion

### ISSUE THREAD

**Issue by DylanGK** [ganymedes01/TheErebus#683]
Bamboo Crates can currently be picked up and retain their inventory. That is fair and well. I just had an idea for them that I believe is more unique and interesting, and provides the players with different choices in a more interesting manner.

**Picking up crates**
Picking up crates should be done with a shift-right click from the Bamboo Wrench. Simply destroying the crate should drop its inventory.

A crate can only be picked up when you do not have anything in your chestplate slot. The crate then embeds itself in there and applies a small slowness effect to the player.

Shift-right clicking the Bamboo Wrench on any non-interactional block will place the Crate.

**Comment by vadis365** [comment]
Extender now rotates on wrench use - no need for shift.
