### ISSUE TITLE
crash when exploring the erebus dimension- already decorating

### ISSUE THREAD

**Issue by 321nick** [ganymedes01/TheErebus#684]
i read the last issue with the already decorating , but it was closed and abandoned, and i still have this issue.

log: https://gist.github.com/c8a7b4247e9d443710c2302d6e68a69d

on 1.7.10 version MP server of erebus

**Comment by 123Kappa** [comment]
https://github.com/vadis365/TheErebus/issues/500 This is from 2016, similar crash. Don't know if it was fixed before and it is happening again

**Comment by vadis365** [comment]
That was a different thing causing it - but the reasons could be the same - although 1.7.10 Erebus hasn't been supported for over 2 years now, so I don't think that will ever be changed.

**Comment by vadis365** [comment]
for ref - as I'll deal with this here rather than pollute the already overloaded sponge issue tracker.
https://github.com/SpongePowered/SpongeForge/issues/2603

**Comment by vadis365** [comment]
I'm going to close this issue as like I have said, the 1.7.10 version is no longer supported or being updated, but this seems to be happening for people in 1.12.2, which I will take a look at.
