### ISSUE TITLE
Crash when entering Erebus (1.12.2) 

### ISSUE THREAD

**Issue by tinyzooseven** [ganymedes01/TheErebus#685]
Q: what mods am I using
A: Project ozone 3with WaitingTime removed

I will ask the admins of the server it is on to give me the logs

**Comment by julianubico** [comment]
I am having this issue as well. Project Ozone 3 v3.0.37
`java.lang.RuntimeException: Already decorating Erebus!`
[crash-2019-01-30_20.54.00-client.txt](https://github.com/vadis365/TheErebus/files/2848471/crash-2019-01-30_20.54.00-client.txt)

**Comment by vadis365** [comment]
@d4fw4ndawg - that crash log shows a completely different error from Tinkers' O.o

**Comment by vadis365** [comment]
moving this to #686 as it's a duplicate issue and will be dealt with there.
