### ISSUE TITLE
The wand of animation Crash.

### ISSUE THREAD

**Issue by D4rkHelix** [ganymedes01/TheErebus#690]
Please make a config to blacklist items that can be used with it too stop insane crashes because it can be used on me systems which causes game to crash and lag like crazy.

**Comment by vadis365** [comment]
Hello,
There is a config file for that already. Be aware it isn't metadata sensitive.
Also mis-use of the wand is on the player not me, why are you using it on ME systems - lol?
Cheers,
Me.
