### ISSUE TITLE
Advancements cannot been translated via lang files...

### ISSUE THREAD

**Issue by VioletWyvern** [ganymedes01/TheErebus#699]
The new advancements was fine, since it make player some challenges to do,  But sadly, these advancements cannot been translated via lang files,  Maybe in the next update?

**Comment by DylanGK** [comment]
Yeah that'll eventually get added. Main priority was no-nonsense getting some advancements out there.

**Comment by DylanGK** [comment]
Alright I had some spare time so I added all advancements to the lang file. Next update will allow all advancements to be translated.
