### ISSUE TITLE
Config File Issues

### ISSUE THREAD

**Issue by PerlerBear** [ganymedes01/TheErebus#700]
Editing the Erebus config file in both the "mod options" in game, or the config file in the mods folder does not work. I have attempted to change the "Spawn Black Widows in Nether", "Random Mob Names", "Play Erebus Songs", and "Coloured Biome Fogs" options to false. None of the options have turned off in game.

**Comment by DylanGK** [comment]
Did you restart your instance after making those changes? 

Currently, most of the changes require a restart to take effect. We may look into changing that for some eventually, but for now: always restart after making changes to the Erebus config.

**Comment by PerlerBear** [comment]
Yes, every time I made a change to the config file I restarted the instance.

**Comment by vadis365** [comment]
Hello,
Are the problems you are experiencing in a single player world or on a server?
A little more information would help us track down the problem you are having.
Could you tell us the mod version you are using?
Cheers,
Me.

**Comment by PerlerBear** [comment]
Single player world
The Jar file reads 1.0.27
I am assuming that is the version.

**Comment by vadis365** [comment]
I would update immediately. That version has a critical crash in it and was archived and a hotfix made.
Although that wouldn't fix your config issue it will stop your game from crashing due to the fly spawner,

**Comment by vadis365** [comment]
I'll take a look tomorrow as we will be testing with the team,

**Comment by vadis365** [comment]
Hello,
I have tested and the config works for me. For some of the things you need to reload the game and not just exit to the main menu.
![biome fogs](https://user-images.githubusercontent.com/6518708/54962769-10452d80-4f5e-11e9-9932-71a2d59feffb.png)
Cheers,
Me.
