### ISSUE TITLE
Dung Spawner Crash while exploring Erebus

### ISSUE THREAD

**Issue by PrimeroBestia** [ganymedes01/TheErebus#704]
I was just exploring Erebus and I keep getting this error about a dung spawner.

Modpack: Project Ozone 3 ver. 3.0.39
Version: Erebus-1.0.27.jar
Minecraft: 1.12.2
Forge: 2815

https://pastebin.com/4pUyysD5

**Comment by vadis365** [comment]
that version of Erebus was pulled because of that error and a hotfix version released - not sure why it's in the modpack. I'd report this to Caz on the PO3 issue tracker.
