### ISSUE TITLE
Return portals just do not generate

### ISSUE THREAD

**Issue by AstralScourge** [ganymedes01/TheErebus#710]
I've went into the erebus quite a few times and so far I haven't seen a single return portal generate at the spot entered. see #663, especially the comment made after the issue was closed.

By "no return portal" I mean that entering the Erebus does not automatically generate the portal back home made of stone bricks/leaves/staff/keystone/whatever, as one would expect.

Issue still occurs with Erebus 1.0.28, Forge 2768

**Comment by vadis365** [comment]
Fixed in dev (finally \o/ ) - will be solved in next release.
