### ISSUE TITLE
Spawned in blocks/suffocation after entering erebus portal

### ISSUE THREAD

**Issue by AstralScourge** [ganymedes01/TheErebus#711]
I created a portal and was thrown inside umberstone.

Mods: Erebus 1.0.28, Forge 14.23.5.2768.
No other mods installed whatsoever

Steps to reproduce:
1. make a world with this seed: 
![image](https://user-images.githubusercontent.com/11131230/54720525-04103900-4b36-11e9-9932-2b9363f6601a.png)
for copy-paste: 5096428351312394144
2. Climb to the nearby hill and make a portal like so:
![image](https://user-images.githubusercontent.com/11131230/54720614-34f06e00-4b36-11e9-8020-b4b37d2f285c.png)
3. Enter, you'll get thrown in umberstone and start suffocating

Would probably be fixed if a return portal was created (see #663) and cleared out an area around where it spawned to ensure this did not happen.

**Comment by vadis365** [comment]
Fixed in dev (finally \o/ ) - will be solved in next release.
