### ISSUE TITLE
Ants dont do specific tasks

### ISSUE THREAD

**Issue by Inonedn** [ganymedes01/TheErebus#713]
Feels like a major issue for ant farming but they can be blocked by lily pads from planting seeds, making it frustrating for putting a proper watering block.

**Comment by vadis365** [comment]
You don't really need a water block if they have a constant supply of compost/bonemeal and enough crops/seeds to plant. You could always just put water on the edges if you really need it.
![ants](https://user-images.githubusercontent.com/6518708/54962716-d83dea80-4f5d-11e9-9d61-aeef9ed7181c.png)
