### ISSUE TITLE
Meet the Beetles! Advancement trigger issue

### ISSUE THREAD

**Issue by ProsperCraft** [ganymedes01/TheErebus#717]
Same as this issue - https://github.com/vadis365/TheErebus/issues/695

The first damage you take by anything when you start a new world you get this advancement.

Meet The Beetles!

**Comment by DylanGK** [comment]
Fixed already for the next update. Sorry for the inconvenience.

**Comment by ProsperCraft** [comment]
Came to report it again, but noticed the update hasn't been pushed yet.
