### ISSUE TITLE
Stag beetle breaking bedrock

### ISSUE THREAD

**Issue by VioletWyvern** [ganymedes01/TheErebus#718]
When you mount the tamed stag beetle and digging the block near the bedrock,  It also breaking the bedrock and created a hole into the void,  This shouldn't be happening...
<a href="https://imgur.com/qXzeKZ6"><img src="https://i.imgur.com/qXzeKZ6.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/XgdSizt"><img src="https://i.imgur.com/XgdSizt.png" title="source: imgur.com" /></a>

**Comment by vadis365** [comment]
fixed in dev.
