### ISSUE TITLE
Black Widows spawning in Nether with config set to off.

### ISSUE THREAD

**Issue by talesofmabria** [ganymedes01/TheErebus#735]
I run a server modpack that adds a lot of mobs to the Nether already.  I used the config, but even with the config set to false for spawning Black Widows, they keep spawning anyway.

**Comment by talesofmabria** [comment]
Also, yes, I've restarted the server several times with the setting turned off.  It just refuses to comply with the change in the config.

**Comment by vadis365** [comment]
Hello, I've added a final failsafe to prevent the widows if the config is set to off now.
The config setting atually works fine for me so I'm not sure what the issue is.

**Comment by talesofmabria** [comment]
It turns out it was another mod that was force generating them, and bypassed the config.  My mistake.
