### ISSUE TITLE
Umber furnace not taking lava from fluid pipe?

### ISSUE THREAD

**Issue by Winddbourne** [ganymedes01/TheErebus#755]
This is really confusing to me. I can use the bamboo fluid/extraction pipes to pump lava from one tank into another but no matter what side I hook the pipe to my Umber Furnace just isn't getting any lava! 

I was honestly worried that the pipes wouldn't take lava, or would burn up when the hot fluid entered them but that isn't what is happening.  This is so weird.

![2019-11-11_18 51 07](https://user-images.githubusercontent.com/24589533/68630138-5a126200-04b4-11ea-92a5-16e28a2f90f2.png)

**Comment by vadis365** [comment]
Fixed in dev - thanks for the report.
