### ISSUE TITLE
Question how to remove death compass 

### ISSUE THREAD

**Issue by k4mix** [ganymedes01/TheErebus#761]
how to remove death compass ? i found  tihs
B:"Block O' Bones Inventory Save"=false 
but i don't have it in my config

**Comment by vadis365** [comment]
It does exist- just nobody seems to be able to read the config.
It has been in the mod since we added the feature in 1.7.10, but people never look in the config
B:"Block O' Bones Inventory Save"=true
just turn that to false
May need a restart - it will turn the compass and the grave off
