### ISSUE TITLE
Add death compass disable to config

### ISSUE THREAD

**Issue by FireImp834** [ganymedes01/TheErebus#774]
With so many options for handling death, it would be nice for mod pack developers to be able to choose to disable the compass. It might be a little more work but you could go so far as to be able to disable it everywhere except when you die in the erebus dimension. Just a simple on/off toggle in the config for enable/disable would probably be sufficient for most though.

**Comment by tyon2006** [comment]
I too would love to see this.

**Comment by vadis365** [comment]
It does exist- just nobody seems to be able to read the config.
It has been in the mod since we added the feature in 1.7.10, but people never look in the config
B:"Block O' Bones Inventory Save"=true
just turn that to false
May need a restart - it will turn the compass and the grave off
