### ISSUE TITLE
Disable Death Compass?

### ISSUE THREAD

**Issue by N1ch0l2s** [ganymedes01/TheErebus#781]
My pack has TombManyGraves which usually gives players a Grave Key when respawning, but this mod overrides that function and gives players a Death Compass instead. Is there any way to disable the death compass? I can't find anything about it in the config files.

**Comment by vadis365** [comment]
It has been in the mod since we added the feature in 1.7.10

B:"Block O' Bones Inventory Save"=true
just turn that to false
may need a restart
it will turn the compass and the grave of.

**Comment by N1ch0l2s** [comment]
Ah, wasn't clear that THAT was the Death Compass....
