### ISSUE TITLE
Further cave decorations [concept, not specified yet]

### ISSUE THREAD

**Issue by Dylan4ever** [ganymedes01/TheErebus#89]
patches of biome-specific blocks in caves (jungle - grass, dirt, gravel, vines; desert - sandstone, sand...)

Such as, jungles having random grassy spots with plants growing on it, and Outback caves being filled with sand, dirt, and shrubs.

The Volcanic Desert would have lots of sand and sandstone in the caves.

Mushrooms would be very widely available in the Fungal Forest.

That kind of stuff.

**Comment by vadis365** [comment]
never happened - probably will re-visit one day....
